import AsyncStorage from "@react-native-async-storage/async-storage";
import React, { createContext, useCallback, useContext, useEffect, useMemo, useState } from "react";

export type Lang = "en" | "ur";

const EN = {
  home: "Home", search: "Search", bookings: "Bookings", profile: "Profile", chat: "Chat",
  dashboard: "Dashboard", jobs: "Jobs", earnings: "Earnings",
  findServices: "Find Services", nearYou: "Near You",
  bookNow: "Book Now", viewAll: "View All", seeAll: "See All",
  services: "Services", topRatedNearby: "Top Rated Nearby",
  workers: "Workers", avgRating: "Avg Rating",
  negotiatePrice: "Negotiate Your Price",
  indriveStyle: "Post your offer — let providers compete",
  makeAnOffer: "Make an Offer",
  emergencyService: "Emergency Service", support247: "24/7 support available", callNow: "Call Now",
  available: "Available", busy: "Busy", newProvider: "New",
  generalServices: "General Services",
  myBookings: "My Bookings", myJobs: "My Jobs", myOffers: "My Offers",
  pending: "Pending", active: "Active", completed: "Completed", cancelled: "Cancelled",
  inProgress: "In Progress", live: "Live", accepted: "Accepted",
  awaitingResponse: "Awaiting Response", providerCountered: "Provider Countered",
  noBookings: "No bookings yet", startExploring: "Find a service and book your first job",
  noOffers: "No price offers yet", negotiateHint: "Go to Search and tap Negotiate Price on a provider",
  totalBookings: "total bookings", priceNegotiations: "price negotiations",
  myProfile: "My Profile", editProfile: "Edit Profile",
  personalInfo: "Personal Information", accountSettings: "Account Settings",
  billingHistory: "Billing History", savedProviders: "Saved Providers",
  myAddresses: "My Addresses", help: "Help & FAQs", about: "About Athoo", privacy: "Privacy & Security",
  logout: "Logout", settings: "Settings",
  notifications: "Notifications", clearAll: "Clear All",
  billing: "Billing", invoices: "Invoices",
  chatbot: "Live Chat Support", saved: "Saved Providers", addresses: "My Addresses",
  bookingsPayments: "Bookings & Payments", account: "Account", support: "Support",
  changePassword: "Change Password", language: "Language",
  welcome: "Welcome Back", signIn: "Sign In", register: "Register",
  forgotPassword: "Forgot Password",
  startJob: "Start Job", completeJob: "Mark Completed",
  acceptJob: "Accept Job", declineJob: "Decline",
  enterOtp: "Enter OTP", sendOtp: "Send OTP", verifyOtp: "Verify OTP",
  otpHint: "Demo OTP: 1234",
  negotiate: "Negotiate Price", makeOffer: "Make Offer",
  accept: "Accept", reject: "Reject", counter: "Counter",
  visitCharge: "Visit Charge", totalAmount: "Total Amount",
  english: "English", urdu: "اردو",
  switchToCustomer: "Switch to Customer", switchToProvider: "Switch to Provider",
  searchPlaceholder: "Search services, workers...",
  allAreas: "All Areas", allServices: "All Services",
  noProviders: "No providers found", tryDifferent: "Try different search or remove filters",
  sortBy: "Sort by", rating: "Rating", totalJobs: "Total Jobs",
  onlyAvailable: "Only Available",
  plumber: "Plumber", electrician: "Electrician", carpenter: "Carpenter",
  painter: "Painter", cleaner: "Cleaner", gardener: "Gardener",
  acRepair: "AC Repair", drain: "Drain/Manhole", welder: "Welder",
  tiler: "Tiler", tankCleaner: "Tank Cleaner", pestControl: "Pest Control",
  providerProfile: "Provider Profile", hireNow: "Hire Now", sendMessage: "Message",
  reviews: "Reviews", experience: "Experience", bio: "About",
  bookService: "Book Service", selectDate: "Select Date", selectTime: "Select Time",
  yourAddress: "Your Address", describeIssue: "Describe the issue",
  totalEarnings: "Total Earnings", weeklyEarnings: "This Week",
  todayEarnings: "Today", jobsDone: "Jobs Done",
  providerDashboard: "Provider Dashboard",
  availableForJobs: "Available for Jobs", notAvailable: "Not Available",
  newRequests: "New Requests", noJobsYet: "No jobs yet", noJobsYetSub: "New bookings will appear here when customers hire you",
  yourPerformance: "Your Performance", earned: "Earned", done: "Done",
  customersCanBook: "Customers can book you now", wontReceive: "You won't receive new requests",
  pendingJobs: "Pending", activeJobs: "Active", completedJobs: "Completed",
  hello: "Hello", bookingHistory: "Booking History",
  newBooking: "New Booking",
  bookPlumber: "Book a Plumber", quickFixes: "Quick fixes & emergency repairs",
  acService: "AC Service", summerReady: "Summer ready in 1 visit",
  deepCleaning: "Deep Cleaning", professionalCleaning: "Professional home sanitization",
  totalSpent: "Total Spent", activeBookings: "Active", completedBookings: "Completed",
  premiumPlan: "Premium Plan", billingHistoryLong: "Past transactions & receipts",
  unlockBenefits: "Unlock exclusive benefits", downloadInvoices: "Download service invoices",
  refundRequests: "Refund Requests", refundRequestsHint: "View & submit refund requests",
  savedServiceLocations: "Saved service locations", favouriteWorkers: "Your favourite workers",
  manageAlerts: "Manage alerts", appearance: "Appearance", appearanceHint: "Light, dark, or device setting",
  updatePassword: "Update your password", languageHint: "English / اردو",
  privacyHint: "Number masking & data", helpHint: "Answers to common questions",
  contactSupport: "Contact Support", contactSupportHint: "Reach our support team",
  aboutHint: "v1.0 · Pakistan", security: "Security", connectWithUs: "Connect With Us",
  dangerZone: "Danger Zone", deactivateAccount: "Deactivate Account", deleteAccount: "Delete Account",
  signOut: "Sign Out", areYouSure: "Are you sure?", cancel: "Cancel",
  totalJobsLabel: "Total Jobs", spent: "Spent", inviteFriends: "Invite Friends",
  inviteFriendsHint: "Share your referral code and earn rewards", share: "Share", referred: "Referred",
  workEarnings: "Work & Earnings", earningsHistory: "Earnings History", myNegotiations: "My Negotiations",
  availabilitySchedule: "Availability Schedule", myWallet: "My Wallet", serviceRadius: "Service Radius",
  providerRole: "Service Provider", verified: "Verified", myServices: "My Services",
  doneLabel: "Done", earnedRs: "Earned Rs.", ratePerHourLabel: "Rs./hr",
  chooseTheme: "Choose your theme", themeHelp: "This preference is saved on this device and applies across Athoo.",
  useDeviceSetting: "Use device setting", deviceSettingHint: "Athoo follows your phone appearance automatically.",
  lightTheme: "Light", lightThemeHint: "Bright backgrounds for daytime use.",
  darkTheme: "Dark", darkThemeHint: "Reduced brightness for low-light use.",
  applyingTheme: "Applying theme…", selectLanguage: "Select language", languageHelp: "Choose the language used across Athoo.",
  englishHint: "Use Athoo in English", urduHint: "اتھو کو اردو میں استعمال کریں", languageApplied: "Language updated",
  welcomeTagline: "Home Services at Your Fingertips", pakistan: "Pakistan", joinAs: "Join as",
  customer: "Customer", customerRoleHint: "Find and hire services", provider: "Provider", providerRoleHint: "Join as a professional",
  verifiedPro: "Verified Pro", alreadyRegistered: "Already registered?", customerSignIn: "Customer Sign In", providerSignIn: "Provider Sign In",
  findSkilledWorkers: "Find skilled workers nearby", liveLocationTracking: "Live location tracking",
  bookNowOrLater: "Book now or schedule later", chatAndCall: "Chat and call in-app", signInWithOtpInstead: "Sign in with OTP instead",
  signInWithFaceId: "Sign in with Face ID", signInWithFingerprint: "Sign in with Fingerprint", signInWithIris: "Sign in with Iris Scan",
  biometricFaceHint: "Look at your phone to sign in instantly", biometricFingerprintHint: "Touch the sensor to sign in instantly",
  biometricIrisHint: "Scan your iris to sign in instantly", sessionExpired: "Session expired — please sign in again.",
  authenticationCancelled: "Authentication cancelled. Try again or use OTP.", back: "Back", selected: "Selected",
};

const UR = {
  home: "ہوم", search: "تلاش", bookings: "بکنگ", profile: "پروفائل", chat: "چیٹ",
  dashboard: "ڈیش بورڈ", jobs: "کام", earnings: "آمدنی",
  findServices: "سروسز تلاش کریں", nearYou: "آپ کے قریب",
  bookNow: "ابھی بک کریں", viewAll: "سب دیکھیں", seeAll: "سب دیکھیں",
  services: "سروسز", topRatedNearby: "قریبی بہترین کاریگر",
  workers: "کاریگر", avgRating: "اوسط ریٹنگ",
  negotiatePrice: "قیمت طے کریں",
  indriveStyle: "اپنی پیشکش دیں — کاریگر مقابلہ کریں",
  makeAnOffer: "پیشکش کریں",
  emergencyService: "ہنگامی سروس", support247: "چوبیس گھنٹے دستیاب", callNow: "ابھی کال کریں",
  available: "دستیاب", busy: "مصروف", newProvider: "نیا",
  generalServices: "عمومی سروسز",
  myBookings: "میری بکنگ", myJobs: "میرے کام", myOffers: "میری پیشکشیں",
  pending: "زیر التواء", active: "فعال", completed: "مکمل", cancelled: "منسوخ",
  inProgress: "جاری ہے", live: "براہ راست", accepted: "قبول شدہ",
  awaitingResponse: "جواب کا انتظار", providerCountered: "کاریگر نے جوابی پیشکش کی",
  noBookings: "ابھی کوئی بکنگ نہیں", startExploring: "سروس تلاش کریں اور پہلا کام بک کریں",
  noOffers: "ابھی کوئی پیشکش نہیں", negotiateHint: "تلاش پر جائیں اور کاریگر پر قیمت طے کریں پر کلک کریں",
  totalBookings: "کل بکنگ", priceNegotiations: "قیمت مذاکرات",
  myProfile: "میرا پروفائل", editProfile: "پروفائل ترمیم",
  personalInfo: "ذاتی معلومات", accountSettings: "اکاؤنٹ سیٹنگز",
  billingHistory: "بلنگ تاریخ", savedProviders: "محفوظ کاریگر",
  myAddresses: "میرے پتے", help: "مدد اور سوالات", about: "اتھو کے بارے میں", privacy: "رازداری و سلامتی",
  logout: "لاگ آوٹ", settings: "سیٹنگز",
  notifications: "اطلاعات", clearAll: "سب صاف کریں",
  billing: "بلنگ", invoices: "انوائس",
  chatbot: "لائیو چیٹ سپورٹ", saved: "محفوظ کاریگر", addresses: "میرے پتے",
  bookingsPayments: "بکنگ اور ادائیگی", account: "اکاؤنٹ", support: "مدد",
  changePassword: "پاسورڈ تبدیل کریں", language: "زبان",
  welcome: "خوش آمدید", signIn: "سائن ان", register: "رجسٹر",
  forgotPassword: "پاسورڈ بھول گئے",
  startJob: "کام شروع کریں", completeJob: "مکمل نشان زد کریں",
  acceptJob: "کام قبول کریں", declineJob: "انکار",
  enterOtp: "OTP درج کریں", sendOtp: "OTP بھیجیں", verifyOtp: "OTP تصدیق کریں",
  otpHint: "ڈیمو OTP: 1234",
  negotiate: "قیمت طے کریں", makeOffer: "پیشکش کریں",
  accept: "قبول", reject: "رد کریں", counter: "جوابی پیشکش",
  visitCharge: "وزٹ چارج", totalAmount: "کل رقم",
  english: "English", urdu: "اردو",
  switchToCustomer: "کسٹمر میں جائیں", switchToProvider: "کاریگر میں جائیں",
  searchPlaceholder: "سروسز، کاریگر تلاش کریں...",
  allAreas: "تمام علاقے", allServices: "تمام سروسز",
  noProviders: "کوئی کاریگر نہیں ملا", tryDifferent: "مختلف تلاش یا فلٹر ہٹائیں",
  sortBy: "ترتیب دیں", rating: "ریٹنگ", totalJobs: "کل کام",
  onlyAvailable: "صرف دستیاب",
  plumber: "پلمبر", electrician: "الیکٹریشن", carpenter: "ترکھان",
  painter: "رنگ ساز", cleaner: "صفائی کار", gardener: "مالی",
  acRepair: "اے سی مرمت", drain: "نالی / مین ہول", welder: "ویلڈر",
  tiler: "ٹائل کار", tankCleaner: "ٹینک صفائی", pestControl: "کیڑے مار",
  providerProfile: "کاریگر پروفائل", hireNow: "ابھی بھرتی کریں", sendMessage: "پیغام",
  reviews: "جائزے", experience: "تجربہ", bio: "تعارف",
  bookService: "سروس بک کریں", selectDate: "تاریخ منتخب کریں", selectTime: "وقت منتخب کریں",
  yourAddress: "آپ کا پتہ", describeIssue: "مسئلہ بیان کریں",
  totalEarnings: "کل آمدنی", weeklyEarnings: "اس ہفتے",
  todayEarnings: "آج", jobsDone: "کام مکمل",
  providerDashboard: "کاریگر ڈیش بورڈ",
  availableForJobs: "کاموں کے لیے دستیاب", notAvailable: "دستیاب نہیں",
  customersCanBook: "کسٹمر ابھی بک کر سکتے ہیں", wontReceive: "نئی درخواستیں نہیں ملیں گی",
  newRequests: "نئی درخواستیں", noJobsYet: "ابھی کوئی کام نہیں", noJobsYetSub: "جب کسٹمر آپ کو ہائر کریں گے تو بکنگ یہاں آئے گی",
  yourPerformance: "آپ کی کارکردگی", earned: "کمائی", done: "مکمل",
  pendingJobs: "زیر التواء", activeJobs: "فعال", completedJobs: "مکمل",
  hello: "ہیلو", bookingHistory: "بکنگ تاریخ",
  newBooking: "نئی بکنگ",
  bookPlumber: "پلمبر بک کریں", quickFixes: "فوری مرمت اور ہنگامی کام",
  acService: "اے سی سروس", summerReady: "ایک وزٹ میں گرمیوں کے لیے تیار",
  deepCleaning: "گہری صفائی", professionalCleaning: "پیشہ ور گھر کی صفائی",
  totalSpent: "کل خرچ", activeBookings: "فعال", completedBookings: "مکمل",
  premiumPlan: "پریمیم پلان", billingHistoryLong: "گزشتہ ادائیگیاں اور رسیدیں",
  unlockBenefits: "خصوصی فوائد حاصل کریں", downloadInvoices: "سروس انوائس ڈاؤن لوڈ کریں",
  refundRequests: "رقم واپسی کی درخواستیں", refundRequestsHint: "درخواستیں دیکھیں اور جمع کریں",
  savedServiceLocations: "محفوظ سروس مقامات", favouriteWorkers: "آپ کے پسندیدہ کاریگر",
  manageAlerts: "اطلاعات کا انتظام", appearance: "ظاہری شکل", appearanceHint: "ہلکا، گہرا یا ڈیوائس سیٹنگ",
  updatePassword: "پاسورڈ اپ ڈیٹ کریں", languageHint: "English / اردو",
  privacyHint: "نمبر ماسکنگ اور ڈیٹا", helpHint: "عام سوالات کے جوابات",
  contactSupport: "سپورٹ سے رابطہ", contactSupportHint: "ہماری سپورٹ ٹیم سے رابطہ کریں",
  aboutHint: "v1.0 · پاکستان", security: "سلامتی", connectWithUs: "ہم سے جڑیں",
  dangerZone: "خطرناک اختیارات", deactivateAccount: "اکاؤنٹ غیر فعال کریں", deleteAccount: "اکاؤنٹ حذف کریں",
  signOut: "سائن آؤٹ", areYouSure: "کیا آپ کو یقین ہے؟", cancel: "منسوخ",
  totalJobsLabel: "کل کام", spent: "خرچ", inviteFriends: "دوستوں کو مدعو کریں",
  inviteFriendsHint: "ریفرل کوڈ شیئر کریں اور انعام حاصل کریں", share: "شیئر", referred: "مدعو کیے",
  workEarnings: "کام اور آمدنی", earningsHistory: "آمدنی کی تاریخ", myNegotiations: "میرے مذاکرات",
  availabilitySchedule: "دستیابی شیڈول", myWallet: "میرا والٹ", serviceRadius: "سروس دائرہ",
  providerRole: "سروس فراہم کنندہ", verified: "تصدیق شدہ", myServices: "میری سروسز",
  doneLabel: "مکمل", earnedRs: "کمائی روپے", ratePerHourLabel: "روپے/گھنٹہ",
  chooseTheme: "اپنی تھیم منتخب کریں", themeHelp: "یہ ترجیح اس ڈیوائس پر محفوظ رہتی ہے اور پوری اتھو ایپ پر لاگو ہوتی ہے۔",
  useDeviceSetting: "ڈیوائس کی سیٹنگ استعمال کریں", deviceSettingHint: "اتھو خودکار طور پر آپ کے فون کی ظاہری شکل اپناتا ہے۔",
  lightTheme: "ہلکی تھیم", lightThemeHint: "دن کے وقت روشن پس منظر۔",
  darkTheme: "گہری تھیم", darkThemeHint: "کم روشنی میں آنکھوں کے لیے آرام دہ۔",
  applyingTheme: "تھیم لاگو ہو رہی ہے…", selectLanguage: "زبان منتخب کریں", languageHelp: "اتھو میں استعمال ہونے والی زبان منتخب کریں۔",
  englishHint: "اتھو کو انگریزی میں استعمال کریں", urduHint: "اتھو کو اردو میں استعمال کریں", languageApplied: "زبان تبدیل ہو گئی",
  welcomeTagline: "گھریلو سروسز آپ کی انگلیوں پر", pakistan: "پاکستان", joinAs: "شامل ہوں بطور",
  customer: "کسٹمر", customerRoleHint: "سروس تلاش کریں اور بک کریں", provider: "سروس فراہم کنندہ", providerRoleHint: "ماہر کے طور پر شامل ہوں",
  verifiedPro: "تصدیق شدہ ماہر", alreadyRegistered: "پہلے سے رجسٹرڈ ہیں؟", customerSignIn: "کسٹمر سائن اِن", providerSignIn: "فراہم کنندہ سائن اِن",
  findSkilledWorkers: "قریبی ماہر کاریگر تلاش کریں", liveLocationTracking: "براہ راست مقام کی نگرانی",
  bookNowOrLater: "ابھی بک کریں یا بعد کے لیے شیڈول کریں", chatAndCall: "ایپ میں چیٹ اور کال", signInWithOtpInstead: "OTP کے ذریعے سائن اِن کریں",
  signInWithFaceId: "فیس آئی ڈی سے سائن اِن", signInWithFingerprint: "فنگر پرنٹ سے سائن اِن", signInWithIris: "آئرس اسکین سے سائن اِن",
  biometricFaceHint: "فوری سائن اِن کے لیے فون کی طرف دیکھیں", biometricFingerprintHint: "فوری سائن اِن کے لیے سینسر چھوئیں",
  biometricIrisHint: "فوری سائن اِن کے لیے آئرس اسکین کریں", sessionExpired: "سیشن ختم ہو گیا — دوبارہ سائن اِن کریں۔",
  authenticationCancelled: "تصدیق منسوخ ہو گئی۔ دوبارہ کوشش کریں یا OTP استعمال کریں۔", back: "واپس", selected: "منتخب",
};


const UR_MESSAGES: Record<string, string> = {
  "Sign in with Biometrics": "بایومیٹرک کے ذریعے سائن اِن کریں",
  "Sign in with {{method}}": "{{method}} کے ذریعے سائن اِن کریں",
  "Invalid Phone": "غلط فون نمبر",
  "Please enter a valid phone number (min 10 digits).": "براہ کرم کم از کم 10 ہندسوں والا درست فون نمبر درج کریں۔",
  "Failed": "ناکام",
  "Unable to send OTP. Please try again.": "OTP بھیجا نہیں جا سکا۔ دوبارہ کوشش کریں۔",
  "OTP Code": "OTP کوڈ",
  "Your OTP: {{code}}\n\nEnter this code below to sign in.": "آپ کا OTP: {{code}}\n\nسائن اِن کے لیے یہ کوڈ نیچے درج کریں۔",
  "Invalid OTP": "غلط OTP",
  "Please enter the 4-digit OTP.": "براہ کرم 4 ہندسوں والا OTP درج کریں۔",
  "Verification Failed": "تصدیق ناکام",
  "Invalid or expired OTP.": "OTP غلط ہے یا اس کی مدت ختم ہو چکی ہے۔",
  "Required": "ضروری",
  "Please enter your email or phone number.": "براہ کرم اپنا ای میل یا فون نمبر درج کریں۔",
  "Please enter your password.": "براہ کرم اپنا پاس ورڈ درج کریں۔",
  "Sign In Failed": "سائن اِن ناکام",
  "Invalid credentials.": "لاگ اِن معلومات درست نہیں ہیں۔",
  "Biometric Login Failed": "بایومیٹرک سائن اِن ناکام",
  "Authentication failed.": "شناخت کی تصدیق ناکام ہو گئی۔",
  "Provider Sign In": "فراہم کنندہ سائن اِن",
  "Welcome Back": "دوبارہ خوش آمدید",
  "Sign in to your service provider account": "اپنے سروس فراہم کنندہ اکاؤنٹ میں سائن اِن کریں",
  "Sign in to book home services": "گھریلو سروسز بک کرنے کے لیے سائن اِن کریں",
  "Service Provider": "سروس فراہم کنندہ",
  "Customer": "کسٹمر",
  "Mobile OTP": "موبائل OTP",
  "Password": "پاس ورڈ",
  "Phone Number": "فون نمبر",
  "Keep me signed in": "مجھے سائن اِن رکھیں",
  "Stays logged in": "سائن اِن برقرار رہے گا",
  "Signs out on close": "ایپ بند ہونے پر سائن آؤٹ",
  "Sending...": "بھیجا جا رہا ہے...",
  "Get OTP Code": "OTP کوڈ حاصل کریں",
  "OTP sent to {{phone}}": "OTP {{phone}} پر بھیج دیا گیا",
  "Your OTP: {{code}}": "آپ کا OTP: {{code}}",
  "Enter 4-digit OTP": "4 ہندسوں والا OTP درج کریں",
  "Verifying...": "تصدیق ہو رہی ہے...",
  "Verify & Sign In": "تصدیق کریں اور سائن اِن ہوں",
  "Change phone number": "فون نمبر تبدیل کریں",
  "Email or Phone": "ای میل یا فون",
  "Enter your email or phone": "اپنا ای میل یا فون درج کریں",
  "Enter your password": "اپنا پاس ورڈ درج کریں",
  "Signing in...": "سائن اِن ہو رہا ہے...",
  "Sign In": "سائن اِن",
  "No password yet? Sign in with OTP first, then set one in your Profile settings.": "ابھی پاس ورڈ نہیں؟ پہلے OTP سے سائن اِن کریں، پھر پروفائل سیٹنگز میں پاس ورڈ مقرر کریں۔",
  "Forgot Password?": "پاس ورڈ بھول گئے؟",
  "New to Athoo?": "اتھو پر نئے ہیں؟",
  "Create an Account": "اکاؤنٹ بنائیں",
  "Invalid Phone Number": "غلط فون نمبر",
  "Please enter a valid Pakistani mobile number (e.g. 03XX-XXXXXXX).": "براہ کرم درست پاکستانی موبائل نمبر درج کریں (مثلاً 03XX-XXXXXXX)۔",
  "Your OTP Code": "آپ کا OTP کوڈ",
  "Code: {{code}}\n\nEnter this code below to continue.": "کوڈ: {{code}}\n\nجاری رکھنے کے لیے یہ کوڈ نیچے درج کریں۔",
  "OTP is wrong or expired.": "OTP غلط ہے یا اس کی مدت ختم ہو چکی ہے۔",
  "Account Already Exists": "اکاؤنٹ پہلے سے موجود ہے",
  "This phone number is already registered as a provider. Please sign in instead.": "یہ فون نمبر پہلے ہی فراہم کنندہ کے طور پر رجسٹرڈ ہے۔ براہ کرم سائن اِن کریں۔",
  "This phone number is already registered. Please sign in instead.": "یہ فون نمبر پہلے ہی رجسٹرڈ ہے۔ براہ کرم سائن اِن کریں۔",
  "Go to Sign In": "سائن اِن پر جائیں",
  "Please enter your full name.": "براہ کرم اپنا پورا نام درج کریں۔",
  "Error": "خرابی",
  "Password must be at least 8 characters": "پاس ورڈ کم از کم 8 حروف کا ہونا چاہیے۔",
  "Please accept the Terms of Service and Privacy Policy to continue.": "جاری رکھنے کے لیے شرائطِ استعمال اور رازداری کی پالیسی قبول کریں۔",
  "Could not create account. Please try again.": "اکاؤنٹ نہیں بن سکا۔ دوبارہ کوشش کریں۔",
  "Create Account": "اکاؤنٹ بنائیں",
  "Verify Phone": "فون کی تصدیق کریں",
  "Your Details": "آپ کی تفصیلات",
  "Enter your phone number to get started": "شروع کرنے کے لیے اپنا فون نمبر درج کریں",
  "We sent a code to {{phone}}": "ہم نے {{phone}} پر کوڈ بھیجا ہے",
  "Almost done! Fill in your details": "تقریباً مکمل! اپنی تفصیلات درج کریں",
  "Get Verification Code": "تصدیقی کوڈ حاصل کریں",
  "4-Digit OTP": "4 ہندسوں والا OTP",
  "Verify & Continue": "تصدیق کریں اور جاری رکھیں",
  "Full Name *": "پورا نام *",
  "Your full name": "آپ کا پورا نام",
  "Email (optional)": "ای میل (اختیاری)",
  "Password *": "پاس ورڈ *",
  "Phone verified: {{phone}}": "فون کی تصدیق ہو گئی: {{phone}}",
  "Creating Account...": "اکاؤنٹ بنایا جا رہا ہے...",
  "Already have an account?": "پہلے سے اکاؤنٹ ہے؟",
  "Reset Password": "پاس ورڈ دوبارہ مقرر کریں",
  "Recover your customer account": "اپنا کسٹمر اکاؤنٹ بحال کریں",
  "Recover your provider account": "اپنا فراہم کنندہ اکاؤنٹ بحال کریں",
  "Customer Account": "کسٹمر اکاؤنٹ",
  "Provider Account": "فراہم کنندہ اکاؤنٹ",
  "Please enter your phone number or email address.": "براہ کرم اپنا فون نمبر یا ای میل درج کریں۔",
  "Dev Mode OTP": "ڈیولپمنٹ OTP",
  "Your OTP is: {{code}}": "آپ کا OTP ہے: {{code}}",
  "Failed to send reset OTP.": "پاس ورڈ ری سیٹ OTP بھیجا نہیں جا سکا۔",
  "Invalid Password": "غلط پاس ورڈ",
  "Password must be at least 8 characters.": "پاس ورڈ کم از کم 8 حروف کا ہونا چاہیے۔",
  "Mismatch": "مماثلت نہیں",
  "New password and confirm password do not match.": "نیا پاس ورڈ اور تصدیقی پاس ورڈ ایک جیسے نہیں ہیں۔",
  "Success": "کامیابی",
  "Password reset successful. Please sign in now.": "پاس ورڈ کامیابی سے تبدیل ہو گیا۔ اب سائن اِن کریں۔",
  "Reset Failed": "ری سیٹ ناکام",
  "Failed to reset password.": "پاس ورڈ ری سیٹ نہیں ہو سکا۔",
  "Send Reset OTP": "ری سیٹ OTP بھیجیں",
  "Verify OTP": "OTP کی تصدیق کریں",
  "New Password": "نیا پاس ورڈ",
  "Confirm New Password": "نئے پاس ورڈ کی تصدیق",
  "Update Password": "پاس ورڈ اپ ڈیٹ کریں",
  "Forgot Password": "پاس ورڈ بھول گئے",
  "Enter your phone number or email to receive a reset OTP.": "ری سیٹ OTP حاصل کرنے کے لیے اپنا فون نمبر یا ای میل درج کریں۔",
  "Enter the OTP sent to your registered contact.": "اپنے رجسٹرڈ رابطے پر بھیجا گیا OTP درج کریں۔",
  "Create a new password for your account.": "اپنے اکاؤنٹ کے لیے نیا پاس ورڈ بنائیں۔",
  "Phone Number or Email": "فون نمبر یا ای میل",
  "OTP sent to {{identifier}}": "OTP {{identifier}} پر بھیج دیا گیا",
  "Enter new password (min 8 chars)": "نیا پاس ورڈ درج کریں (کم از کم 8 حروف)",
  "Confirm Password": "پاس ورڈ کی تصدیق",
  "Confirm new password": "نئے پاس ورڈ کی تصدیق کریں",
  "Updating...": "اپ ڈیٹ ہو رہا ہے...",
  "Provider Registration": "فراہم کنندہ رجسٹریشن",
  "Join Athoo as a verified professional": "تصدیق شدہ ماہر کے طور پر اتھو میں شامل ہوں",
  "Personal Info": "ذاتی معلومات",
  "Basic details": "بنیادی تفصیلات",
  "Documents": "دستاویزات",
  "CNIC & certificates": "شناختی کارڈ اور سرٹیفکیٹس",
  "Verification": "تصدیق",
  "Phone & review": "فون اور جائزہ",
  "CNIC Front": "شناختی کارڈ کا سامنے والا حصہ",
  "CNIC Back": "شناختی کارڈ کا پچھلا حصہ",
  "Live Selfie": "براہ راست سیلفی",
  "Introduction Video": "تعارفی ویڈیو",
  "Diploma / Certificate": "ڈپلومہ / سرٹیفکیٹ",
  "Police Verification Letter": "پولیس تصدیقی خط",
  "Clear photo of your CNIC front side": "اپنے شناختی کارڈ کے سامنے والے حصے کی صاف تصویر",
  "Clear photo of your CNIC back side": "اپنے شناختی کارڈ کے پچھلے حصے کی صاف تصویر",
  "Take a selfie holding your CNIC": "شناختی کارڈ پکڑ کر سیلفی لیں",
  "Short 30-second intro video (optional)": "30 سیکنڈ کی مختصر تعارفی ویڈیو (اختیاری)",
  "Any relevant qualification or trade certificate": "متعلقہ قابلیت یا فنی سرٹیفکیٹ",
  "Character certificate from your local police station — mandatory for verification": "مقامی پولیس اسٹیشن کا کریکٹر سرٹیفکیٹ — تصدیق کے لیے لازمی",
  "Replace or Remove": "تبدیل کریں یا ہٹائیں",
  'What would you like to do with "{{label}}"?': 'آپ "{{label}}" کے ساتھ کیا کرنا چاہتے ہیں؟',
  "Keep": "رکھیں",
  "Replace": "تبدیل کریں",
  "Remove": "ہٹائیں",
  "Upload Document": "دستاویز اپ لوڈ کریں",
  'Choose source for "{{label}}"': '"{{label}}" کے لیے ذریعہ منتخب کریں',
  "Camera": "کیمرہ",
  "Gallery": "گیلری",
  "Camera Permission Required": "کیمرہ اجازت درکار ہے",
  "Please go to Settings → Athoo (or Expo Go) → allow Camera access, then try again.": "سیٹنگز → Athoo (یا Expo Go) میں جا کر کیمرہ کی اجازت دیں، پھر دوبارہ کوشش کریں۔",
  "Camera Error": "کیمرہ خرابی",
  "Could not open camera. Please try gallery instead.": "کیمرہ نہیں کھل سکا۔ گیلری سے کوشش کریں۔",
  "Gallery Permission Required": "گیلری اجازت درکار ہے",
  "Please go to Settings → Athoo (or Expo Go) → allow Photos access, then try again.": "سیٹنگز → Athoo (یا Expo Go) میں جا کر تصاویر کی اجازت دیں، پھر دوبارہ کوشش کریں۔",
  "Gallery Error": "گیلری خرابی",
  "Could not open photo library. Please try again.": "تصویری گیلری نہیں کھل سکی۔ دوبارہ کوشش کریں۔",
  "Please fill all required fields marked with *": "* سے نشان زد تمام لازمی خانے پُر کریں۔",
  "Invalid CNIC": "غلط شناختی کارڈ نمبر",
  "Enter a valid 13-digit CNIC number.": "درست 13 ہندسوں والا شناختی کارڈ نمبر درج کریں۔",
  "Phone Not Verified": "فون کی تصدیق نہیں ہوئی",
  "Please verify your phone number before continuing.": "جاری رکھنے سے پہلے اپنے فون نمبر کی تصدیق کریں۔",
  "Services Required": "سروس منتخب کرنا ضروری ہے",
  "Select at least one service you offer.": "کم از کم ایک فراہم کردہ سروس منتخب کریں۔",
  "Documents Required": "دستاویزات درکار ہیں",
  "Please upload CNIC front, CNIC back, a live selfie, and the police verification letter.": "شناختی کارڈ کے دونوں رخ، براہ راست سیلفی اور پولیس تصدیقی خط اپ لوڈ کریں۔",
  "Registration saved — documents need attention": "رجسٹریشن محفوظ ہو گئی — دستاویزات پر توجہ درکار ہے",
  "Your account was created, but these required documents did not upload: {{documents}}. Please upload them again from Verification Documents.": "آپ کا اکاؤنٹ بن گیا، مگر یہ لازمی دستاویزات اپ لوڈ نہیں ہوئیں: {{documents}}۔ تصدیقی دستاویزات سے دوبارہ اپ لوڈ کریں۔",
  "Manage Documents": "دستاویزات کا انتظام",
  "Registration Error": "رجسٹریشن خرابی",
  "Personal Information": "ذاتی معلومات",
  "Full Name": "پورا نام",
  "As on CNIC": "شناختی کارڈ کے مطابق",
  "Father's Name": "والد کا نام",
  "Father's full name": "والد کا پورا نام",
  "CNIC Number": "شناختی کارڈ نمبر",
  "Phone number verified": "فون نمبر کی تصدیق ہو گئی",
  "Enter phone number first": "پہلے فون نمبر درج کریں",
  "Code: {{code}}\n\nEnter this code in the field below.": "کوڈ: {{code}}\n\nیہ کوڈ نیچے درج کریں۔",
  "Send Verification Code": "تصدیقی کوڈ بھیجیں",
  "OTP code: {{code}}": "OTP کوڈ: {{code}}",
  "Email Address": "ای میل ایڈریس",
  "Services & Details": "سروسز اور تفصیلات",
  "Services Offered": "فراہم کردہ سروسز",
  "Years of Experience": "تجربے کے سال",
  "e.g. 5 years": "مثلاً 5 سال",
  "Hourly Rate (PKR)": "فی گھنٹہ معاوضہ (روپے)",
  "Professional Bio": "پیشہ ورانہ تعارف",
  "Describe your expertise, experience, and what makes you the best choice...": "اپنی مہارت، تجربہ اور اپنی نمایاں خوبیوں کے بارے میں لکھیں...",
  "Area/Address": "علاقہ / پتہ",
  "Your working area": "آپ کا کام کا علاقہ",
  "Document Upload": "دستاویز اپ لوڈ",
  "All documents are encrypted and reviewed only by Athoo's verification team. Your data is never shared publicly.": "تمام دستاویزات محفوظ انداز میں رکھی جاتی ہیں اور صرف اتھو کی تصدیقی ٹیم دیکھتی ہے۔ آپ کا ڈیٹا عوامی طور پر شیئر نہیں کیا جاتا۔",
  "✓ Uploaded — tap to replace or remove": "✓ اپ لوڈ ہو گیا — تبدیل یا ہٹانے کے لیے ٹیپ کریں",
  "📷 Tap to open camera": "📷 کیمرہ کھولنے کے لیے ٹیپ کریں",
  "📁 Tap for camera or gallery": "📁 کیمرہ یا گیلری کے لیے ٹیپ کریں",
  "Police Verification": "پولیس تصدیق",
  "After registration, our team will guide you through the police character certificate verification process. This builds customer trust and helps you get more bookings.": "رجسٹریشن کے بعد ہماری ٹیم پولیس کریکٹر سرٹیفکیٹ کی تصدیق میں رہنمائی کرے گی۔ اس سے کسٹمر کا اعتماد بڑھتا ہے اور مزید بکنگ ملتی ہیں۔",
  "Under Review": "زیرِ جائزہ",
  "Your Application is Being Reviewed": "آپ کی درخواست کا جائزہ لیا جا رہا ہے",
  "Our team will verify your documents, CNIC, and police verification within 24-48 hours. You'll receive a notification once approved.": "ہماری ٹیم 24 سے 48 گھنٹوں میں دستاویزات، شناختی کارڈ اور پولیس تصدیق کا جائزہ لے گی۔ منظوری پر اطلاع ملے گی۔",
  "Identity verification (CNIC)": "شناختی تصدیق (شناختی کارڈ)",
  "Document authenticity check": "دستاویزات کی اصلیت کی جانچ",
  "Police background check": "پولیس پس منظر کی جانچ",
  "Skills & experience review": "مہارت اور تجربے کا جائزہ",
  "Summary": "خلاصہ",
  "Name": "نام",
  "Phone": "فون",
  "Services": "سروسز",
  "{{count}} selected": "{{count}} منتخب",
  "{{uploaded}}/{{total}} uploaded": "{{uploaded}}/{{total}} اپ لوڈ",
  "I declare that all the information and documents provided above are true, accurate, and to the best of my knowledge.": "میں تصدیق کرتا ہوں کہ اوپر دی گئی تمام معلومات اور دستاویزات میرے علم کے مطابق درست اور مکمل ہیں۔",
  "Submitting...": "جمع ہو رہا ہے...",
  "Submit Application": "درخواست جمع کریں",
  "Continue": "جاری رکھیں",
  "Important Notice": "اہم اطلاع",
  "Please add all your information exactly as it appears on your CNIC and other legal documents. False or incorrect details will lead to rejection of your application and may result in a permanent ban.": "تمام معلومات شناختی کارڈ اور قانونی دستاویزات کے عین مطابق درج کریں۔ غلط معلومات درخواست مسترد ہونے اور مستقل پابندی کا سبب بن سکتی ہیں۔",
  "I Understand, Continue": "میں سمجھ گیا، جاری رکھیں",
  "Phone Verification": "فون کی تصدیق",
  "Enter the 4-digit code shown below": "نیچے دکھایا گیا 4 ہندسوں والا کوڈ درج کریں",
  "Invalid Code": "غلط کوڈ",
  "The code you entered is incorrect. Check the code shown above.": "درج کیا گیا کوڈ غلط ہے۔ اوپر دکھایا گیا کوڈ چیک کریں۔",
  "This phone number is already registered as a customer. Please sign in instead.": "یہ فون نمبر پہلے ہی کسٹمر کے طور پر رجسٹرڈ ہے۔ براہ کرم سائن اِن کریں۔",
  "Application Submitted!": "درخواست جمع ہو گئی!",
  "Your provider registration is under review. Our team will verify your documents and approve your account within 24-48 hours.": "آپ کی فراہم کنندہ رجسٹریشن زیرِ جائزہ ہے۔ ہماری ٹیم 24 سے 48 گھنٹوں میں دستاویزات کی تصدیق کر کے اکاؤنٹ منظور کرے گی۔",
  "Go to Home": "ہوم پر جائیں",
  "Back to Login": "لاگ اِن پر واپس جائیں",
  "Earnings": "آمدنی",
  "Messages": "پیغامات",
  "Delete Chat": "چیٹ حذف کریں",
  "Are you sure you want to delete your chat with {{name}}? This action cannot be undone.": "کیا آپ {{name}} کے ساتھ چیٹ حذف کرنا چاہتے ہیں؟ یہ عمل واپس نہیں ہو سکتا۔",
  "Delete": "حذف کریں",
  "Failed to delete chat. Please try again.": "چیٹ حذف نہیں ہو سکی۔ دوبارہ کوشش کریں۔",
  "Find a provider to message": "پیغام کے لیے فراہم کنندہ تلاش کریں",
  "No messages yet": "ابھی کوئی پیغام نہیں",
  "Book a service to start chatting with providers": "فراہم کنندہ سے چیٹ شروع کرنے کے لیے سروس بک کریں",
  "Customer messages will appear here": "کسٹمر کے پیغامات یہاں نظر آئیں گے",
  "Open chat with {{name}}": "{{name}} کے ساتھ چیٹ کھولیں",
  "now": "ابھی",
  "Review Submitted": "جائزہ جمع ہو گیا",
  "Thank you for your feedback!": "آپ کی رائے کا شکریہ!",
  "Could not submit rating. Please try again.": "ریٹنگ جمع نہیں ہو سکی۔ دوبارہ کوشش کریں۔",
  "Could not open chat. Please try again.": "چیٹ نہیں کھل سکی۔ دوبارہ کوشش کریں۔",
  "No price offers yet": "ابھی قیمت کی کوئی پیشکش نہیں",
  "Negotiate prices with providers on their profile pages": "فراہم کنندگان کے پروفائل پر قیمت طے کریں",
  "Browse Services": "سروسز دیکھیں",
  "with {{name}}": "{{name}} کے ساتھ",
  "Your Offer": "آپ کی پیشکش",
  "Counter": "جوابی پیشکش",
  "Agreed": "طے شدہ",
  "Location permission": "مقام کی اجازت",
  "Athoo uses your location to show nearby providers and choose an address.": "اتھو آپ کے مقام سے قریبی فراہم کنندگان دکھاتا اور پتہ منتخب کرتا ہے۔",
  "Recommended": "تجویز کردہ",
  "Nearest": "قریب ترین",
  "Top Rated": "بہترین ریٹنگ",
  "Most Jobs": "سب سے زیادہ کام",
  "Map available in mobile app": "نقشہ موبائل ایپ میں دستیاب ہے",
  "Getting address...": "پتہ حاصل کیا جا رہا ہے...",
  "Picked from map": "نقشے سے منتخب",
  "Selected Address": "منتخب پتہ",
  "Your name": "آپ کا نام",
  "Verified Customer": "تصدیق شدہ کسٹمر",
  "New Broadcast Job!": "نیا براڈکاسٹ کام!",
  "Service request": "سروس کی درخواست",
  "Customer Offer": "کسٹمر کی پیشکش",
  "Dismiss": "بند کریں",
  "View Job": "کام دیکھیں",
  "new": "نئے",
  "Total": "کل",
  "No negotiations": "کوئی مذاکرات نہیں",
  "Customer price offers will appear here when a booking enters negotiation.": "بکنگ کے مذاکرات میں آنے پر کسٹمر کی قیمت کی پیشکشیں یہاں نظر آئیں گی۔",
  "Total Earned": "کل کمائی",
  "Average per job": "فی کام اوسط",
  "All": "سب",
  "Broadcast Request": "براڈکاسٹ درخواست",
  "Commission Overview": "کمیشن کا خلاصہ",
  "Commission is 10% per booking, deducted from your earnings on completion.": "ہر بکنگ پر 10٪ کمیشن مکمل ہونے کے بعد آپ کی آمدنی سے منہا کیا جاتا ہے۔",
  "Countered": "جوابی پیشکش دی گئی",
  "Earnings will appear here once you complete bookings": "بکنگ مکمل کرنے کے بعد آمدنی یہاں نظر آئے گی",
  "From": "کی طرف سے",
  "Got it": "سمجھ گیا",
  "Hello, {{name}} 👋": "سلام، {{name}} 👋",
  "Jobs will appear here when customers book your services.": "کسٹمر آپ کی سروس بک کریں گے تو کام یہاں نظر آئیں گے۔",
  "Monthly Limit": "ماہانہ حد",
  "Negotiations": "مذاکرات",
  "No completed jobs this week": "اس ہفتے کوئی مکمل کام نہیں",
  "No completed jobs yet": "ابھی کوئی مکمل کام نہیں",
  "No jobs here": "یہاں کوئی کام نہیں",
  "No live jobs": "کوئی جاری کام نہیں",
  "Offer": "پیشکش",
  "Pending Due": "واجب الادا",
  "Recent Completed Jobs": "حالیہ مکمل کام",
  "Rejected": "مسترد",
  "Retry": "دوبارہ کوشش",
  "Rs.": "روپے",
  "Total Deducted": "کل منہا",
  "Waiting for providers to respond...": "فراہم کنندگان کے جواب کا انتظار ہے...",
  "You have no jobs in progress right now.": "اس وقت کوئی کام جاری نہیں۔",
  "Your Counter": "آپ کی جوابی پیشکش",
  "there": "دوست",
  "total": "کل",
  "Tap to retry.": "دوبارہ کوشش کے لیے ٹیپ کریں۔",
  "Some home content could not be refreshed. Pull down or tap retry.": "ہوم کا کچھ مواد تازہ نہیں ہو سکا۔ نیچے کھینچیں یا دوبارہ کوشش کریں۔",
  "Could not load provider dashboard": "فراہم کنندہ ڈیش بورڈ لوڈ نہیں ہو سکا",
  "Provider": "فراہم کنندہ",
  "Contact {{role}}": "{{role}} سے رابطہ کریں",
  "Opens booking details": "بکنگ کی تفصیلات کھولتا ہے",
  "profile photo": "پروفائل تصویر",
  "Tap to rate this job": "اس کام کو ریٹ کرنے کے لیے ٹیپ کریں",
  "Close OTP dialog": "OTP ڈائیلاگ بند کریں",
  "Enter the 4-digit OTP": "چار ہندسوں والا OTP درج کریں",
  "Unable to resend OTP. Please try again.": "OTP دوبارہ نہیں بھیجا جا سکا۔ دوبارہ کوشش کریں۔",
  "Sent to: {{destination}}": "بھیجا گیا: {{destination}}",
  "Your code:": "آپ کا کوڈ:",
  "OTP digit {{position}} of 4": "OTP کا ہندسہ {{position}} از 4",
  "Entered": "درج ہے",
  "Empty": "خالی",
  "Verifying…": "تصدیق ہو رہی ہے…",
  "Resend available in {{seconds}} seconds": "OTP {{seconds}} سیکنڈ بعد دوبارہ بھیجا جا سکتا ہے",
  "Resend in {{seconds}}s": "{{seconds}} سیکنڈ بعد دوبارہ بھیجیں",
  "Resend OTP": "OTP دوبارہ بھیجیں",
  "Sending…": "بھیجا جا رہا ہے…",
  "Cancel": "منسوخ",
  "Close dialog": "ڈائیلاگ بند کریں",
  "Back": "واپس",
  "Billing & History": "بلنگ اور تاریخ",
  "Total Spent": "کل خرچ",
  "Completed Jobs": "مکمل کام",
  "No transactions": "کوئی لین دین نہیں",
  "Your billing history will appear here": "آپ کی بلنگ تاریخ یہاں نظر آئے گی",
  "TBD": "بعد میں طے ہوگا",
  "Payments are made directly to the provider in cash. Athoo never handles your money or stores payment details.": "ادائیگی براہ راست فراہم کنندہ کو نقد کی جاتی ہے۔ اتھو آپ کی رقم نہیں سنبھالتا اور ادائیگی کی تفصیلات محفوظ نہیں کرتا۔",
  "Loading wallet": "والٹ لوڈ ہو رہا ہے",
  "Loading wallet…": "والٹ لوڈ ہو رہا ہے…",
  "Could not load wallet. Please try again.": "والٹ لوڈ نہیں ہو سکا۔ دوبارہ کوشش کریں۔",
  "My Wallet": "میرا والٹ",
  "Total Job Earnings": "کاموں کی کل آمدنی",
  "{{count}} completed jobs": "{{count}} مکمل کام",
  "Paid to Athoo": "اتھو کو ادا شدہ",
  "Pending Dues": "واجب الادا",
  "Dues Remaining": "باقی حد",
  "Wallet unavailable": "والٹ دستیاب نہیں",
  "Commission Dues Outstanding": "کمیشن کی واجب الادا رقم",
  "Pay Athoo to keep your account active": "اکاؤنٹ فعال رکھنے کے لیے اتھو کو ادائیگی کریں",
  "Commission limit used": "استعمال شدہ کمیشن حد",
  "Limit: {{amount}} · {{percent}}% used": "حد: {{amount}} · {{percent}}٪ استعمال",
  "Pay Commission Dues": "کمیشن واجبات ادا کریں",
  "Earnings History": "آمدنی کی تاریخ",
  "View Invoices": "انوائس دیکھیں",
  "Finance Support": "مالی معاونت",
  "Commission Total": "کل کمیشن",
  "Recent Earnings": "حالیہ آمدنی",
  "Complete jobs to see your earnings here": "اپنی آمدنی یہاں دیکھنے کے لیے کام مکمل کریں",
  "commission": "کمیشن",
  "Net Earnings": "خالص آمدنی",
  "Active Jobs": "فعال کام",
  "Athoo Commission": "اتھو کمیشن",
  "Pending Athoo commission:": "اتھو کا واجب الادا کمیشن:",
  "Limit: {{amount}}": "حد: {{amount}}",
  "New jobs are blocked until payment is cleared.": "ادائیگی صاف ہونے تک نئے کام بند ہیں۔",
  "Keep your dues below the limit to continue receiving orders.": "آرڈرز جاری رکھنے کے لیے واجبات حد سے کم رکھیں۔",
  "This Month": "اس ماہ",
  "All Time": "تمام مدت",
  "Earnings Chart": "آمدنی کا چارٹ",
  "Earnings chart for {{period}}": "{{period}} کے لیے آمدنی کا چارٹ",
  "Customer: {{name}}": "کسٹمر: {{name}}",
  "Recent": "حالیہ",
  "Gross {{gross}} · Athoo {{commission}}": "مجموعی {{gross}} · اتھو {{commission}}",
  "COMPLETED": "مکمل",
  "No Earnings Yet": "ابھی کوئی آمدنی نہیں",
  "Complete jobs to see your provider earnings and Athoo commission here.": "اپنی آمدنی اور اتھو کمیشن یہاں دیکھنے کے لیے کام مکمل کریں۔",
  "Mon": "پیر",
  "Tue": "منگل",
  "Wed": "بدھ",
  "Thu": "جمعرات",
  "Fri": "جمعہ",
  "Sat": "ہفتہ",
  "Sun": "اتوار",
  "Wk {{week}}": "ہفتہ {{week}}",
  "Jan": "جنوری",
  "Feb": "فروری",
  "Mar": "مارچ",
  "Apr": "اپریل",
  "May": "مئی",
  "Jun": "جون",
  "Jul": "جولائی",
  "Aug": "اگست",
  "Sep": "ستمبر",
  "Oct": "اکتوبر",
  "Nov": "نومبر",
  "Dec": "دسمبر",
  "1. Select Athoo Payment Account": "1. Athoo کا ادائیگی اکاؤنٹ منتخب کریں",
  "2. Fill in Payment Details": "2. ادائیگی کی تفصیلات درج کریں",
  "Account Number / EasyPaisa / JazzCash *": "اکاؤنٹ نمبر / ایزی پیسہ / جاز کیش *",
  "Account Title *": "اکاؤنٹ کا عنوان *",
  "Account number required": "اکاؤنٹ نمبر درکار ہے",
  "Account title required": "اکاؤنٹ کا عنوان درکار ہے",
  "Add payment screenshot": "ادائیگی کا اسکرین شاٹ شامل کریں",
  "Add photo evidence": "تصویری ثبوت شامل کریں",
  "Amount": "رقم",
  "Amount (Rs.) *": "رقم (روپے) *",
  "Amount Due": "واجب الادا رقم",
  "Amount Too High": "رقم بہت زیادہ ہے",
  "Amount cannot exceed the available commission amount ({{amount}}).": "رقم دستیاب کمیشن ({{amount}}) سے زیادہ نہیں ہو سکتی۔",
  "Are you sure you want to cancel your current plan?": "کیا آپ واقعی اپنا موجودہ پلان منسوخ کرنا چاہتے ہیں؟",
  "Athoo Premium": "Athoo پریمیم",
  "Attach Payment Screenshot": "ادائیگی کا اسکرین شاٹ منسلک کریں",
  "Attach Photo Evidence": "تصویری ثبوت منسلک کریں",
  "BILLED TO": "بل برائے",
  "Bank Name (optional)": "بینک کا نام (اختیاری)",
  "Boost your visibility & unlock features": "اپنی نمایاں حیثیت بڑھائیں اور مزید خصوصیات حاصل کریں",
  "CURRENT PLAN": "موجودہ پلان",
  "Camera or gallery": "کیمرہ یا گیلری",
  "Cancel Plan": "پلان منسوخ کریں",
  "Cancel Subscription": "سبسکرپشن منسوخ کریں",
  "Cancellation Scheduled": "منسوخی طے ہو گئی",
  "Credit Limit": "کریڈٹ حد",
  "Describe why you need a refund (minimum 10 characters)": "رقم واپسی کی وجہ بیان کریں (کم از کم 10 حروف)",
  "Description": "تفصیل",
  "Discount": "رعایت",
  "Enter amount to refund": "واپسی کی رقم درج کریں",
  "Failed to Load": "لوڈ نہیں ہو سکا",
  "Fixed visit fee": "مقررہ وزٹ فیس",
  "Get more out of every booking": "ہر بکنگ سے مزید فوائد حاصل کریں",
  "How to pay": "ادائیگی کا طریقہ",
  "IBAN (optional)": "آئی بین (اختیاری)",
  "Invalid Amount": "غلط رقم",
  "Invoice Details": "انوائس کی تفصیلات",
  "Invoice ready": "انوائس تیار ہے",
  "Invoices appear after service completion": "سروس مکمل ہونے کے بعد انوائس یہاں ظاہر ہوں گے",
  "Invoices unavailable": "انوائس دستیاب نہیں",
  "Keep Plan": "پلان برقرار رکھیں",
  "Loading refunds…": "رقم واپسی کی درخواستیں لوڈ ہو رہی ہیں…",
  "Loading withdrawals…": "رقم نکلوانے کی درخواستیں لوڈ ہو رہی ہیں…",
  "Loading...": "لوڈ ہو رہا ہے…",
  "Minimum withdrawal amount is Rs. 500.": "کم از کم رقم نکلوانے کی حد 500 روپے ہے۔",
  "Monthly": "ماہانہ",
  "My Invoices": "میرے انوائس",
  "New Refund Request": "نئی رقم واپسی درخواست",
  "New Withdrawal Request": "نئی رقم نکلوانے کی درخواست",
  "No Dues Outstanding": "کوئی واجب الادا رقم نہیں",
  "No Invoices Yet": "ابھی کوئی انوائس نہیں",
  "No Refund Requests": "کوئی رقم واپسی درخواست نہیں",
  "No Withdrawal Requests": "کوئی رقم نکلوانے کی درخواست نہیں",
  "No invoices yet": "ابھی کوئی انوائس نہیں",
  "No plans available": "کوئی پلان دستیاب نہیں",
  "Note (optional)": "نوٹ (اختیاری)",
  "Our team will review your request within 24-48 hours.": "ہماری ٹیم 24 سے 48 گھنٹوں میں آپ کی درخواست کا جائزہ لے گی۔",
  "PAID": "ادا شدہ",
  "Payment History": "ادائیگی کی تاریخ",
  "Payment Screenshot": "ادائیگی کا اسکرین شاٹ",
  "Payment Submitted": "ادائیگی جمع ہو گئی",
  "Payment details unavailable": "ادائیگی کی تفصیلات دستیاب نہیں",
  "Payment reference required": "ادائیگی کا حوالہ درکار ہے",
  "Payment screenshot required": "ادائیگی کا اسکرین شاٹ درکار ہے",
  "Pending Approval": "منظوری کا منتظر",
  "Pending Request": "درخواست زیر التوا ہے",
  "Photo Evidence (optional)": "تصویری ثبوت (اختیاری)",
  "Photo unavailable": "تصویر دستیاب نہیں",
  "Please add a payment screenshot before submitting.": "جمع کرنے سے پہلے ادائیگی کا اسکرین شاٹ شامل کریں۔",
  "Please add the payment receipt screenshot.": "ادائیگی کی رسید کا اسکرین شاٹ شامل کریں۔",
  "Please describe the reason (at least 10 characters).": "براہ کرم وجہ بیان کریں (کم از کم 10 حروف)۔",
  "Please enter a valid amount greater than zero.": "صفر سے زیادہ درست رقم درج کریں۔",
  "Please enter a valid refund amount.": "رقم واپسی کی درست رقم درج کریں۔",
  "Please enter the account or mobile wallet number.": "اکاؤنٹ یا موبائل والٹ نمبر درج کریں۔",
  "Please enter the account title.": "اکاؤنٹ کا عنوان درج کریں۔",
  "Please enter the transaction reference number or TID from your receipt.": "رسید سے ٹرانزیکشن حوالہ نمبر یا TID درج کریں۔",
  "Please enter your payment reference or transaction ID.": "ادائیگی کا حوالہ یا ٹرانزیکشن آئی ڈی درج کریں۔",
  "Please select the Athoo payment account you paid to.": "وہ Athoo ادائیگی اکاؤنٹ منتخب کریں جس پر آپ نے رقم بھیجی۔",
  "Please select the booking you want a refund for.": "وہ بکنگ منتخب کریں جس کے لیے رقم واپسی چاہتے ہیں۔",
  "Premium Active": "پریمیم فعال ہے",
  "Premium Plans": "پریمیم پلانز",
  "Premium plans coming soon!": "پریمیم پلان جلد آ رہے ہیں!",
  "Premium plans will be available soon.": "پریمیم پلان جلد دستیاب ہوں گے۔",
  "Provider Amount": "فراہم کنندہ کی رقم",
  "Provider Earnings": "فراہم کنندہ کی آمدنی",
  "Reason *": "وجہ *",
  "Reason Required": "وجہ درکار ہے",
  "Reference Required": "حوالہ نمبر درکار ہے",
  "Refund Amount (Rs.) *": "رقم واپسی (روپے) *",
  "Refund History": "رقم واپسی کی تاریخ",
  "Refund Requests": "رقم واپسی درخواستیں",
  "Refund Submitted": "رقم واپسی درخواست جمع ہو گئی",
  "Remove & replace": "ہٹائیں اور تبدیل کریں",
  "Request History": "درخواستوں کی تاریخ",
  "Request Submitted": "درخواست جمع ہو گئی",
  "Request a Refund": "رقم واپسی کی درخواست دیں",
  "Request a refund for completed bookings": "مکمل بکنگ کے لیے رقم واپسی کی درخواست دیں",
  "Request submitted": "درخواست جمع ہو گئی",
  "Request your earnings payout": "اپنی آمدنی کی ادائیگی کی درخواست دیں",
  "SERVICE BY": "سروس فراہم کنندہ",
  "Screenshot Required": "اسکرین شاٹ درکار ہے",
  "Search by service...": "سروس کے ذریعے تلاش کریں…",
  "Select Account": "اکاؤنٹ منتخب کریں",
  "Select Booking": "بکنگ منتخب کریں",
  "Select Booking *": "بکنگ منتخب کریں *",
  "Service": "سروس",
  "Stay tuned for exclusive member benefits.": "خصوصی ممبر فوائد کے لیے منتظر رہیں۔",
  "Submission Failed": "درخواست جمع نہیں ہو سکی",
  "Submit Refund Request": "رقم واپسی درخواست جمع کریں",
  "Submit Request": "درخواست جمع کریں",
  "Submit for Approval": "منظوری کے لیے جمع کریں",
  "Subscription History": "سبسکرپشن کی تاریخ",
  "Subscription cancelled": "سبسکرپشن منسوخ ہو گئی",
  "Subtotal": "ذیلی مجموعہ",
  "TOTAL PAID": "کل ادا شدہ",
  "Take a new photo or choose one from your gallery.": "نئی تصویر لیں یا گیلری سے منتخب کریں۔",
  "Tax (0%)": "ٹیکس (0٪)",
  "Thank you for using Athoo!": "Athoo استعمال کرنے کا شکریہ!",
  "Transaction / Reference ID": "ٹرانزیکشن / حوالہ آئی ڈی",
  "Unable to cancel subscription": "سبسکرپشن منسوخ نہیں ہو سکی",
  "Unable to create invoice": "انوائس نہیں بن سکا",
  "Unable to load refunds": "رقم واپسی درخواستیں لوڈ نہیں ہو سکیں",
  "Unable to submit refund": "رقم واپسی درخواست جمع نہیں ہو سکی",
  "Unable to submit request": "درخواست جمع نہیں ہو سکی",
  "Upload Failed": "اپ لوڈ ناکام رہا",
  "Uploading…": "اپ لوڈ ہو رہا ہے…",
  "Used": "استعمال شدہ",
  "Visit / Call-out Charge": "وزٹ / کال آؤٹ چارج",
  "Visit Charge": "وزٹ چارج",
  "We couldn't cancel your subscription. Please try again.": "سبسکرپشن منسوخ نہیں ہو سکی۔ دوبارہ کوشش کریں۔",
  "We couldn't create the invoice PDF. Please try again.": "انوائس PDF نہیں بن سکا۔ دوبارہ کوشش کریں۔",
  "We couldn't load commission payment details. Please try again.": "کمیشن ادائیگی کی تفصیلات لوڈ نہیں ہو سکیں۔ دوبارہ کوشش کریں۔",
  "We couldn't load subscription plans. Please try again.": "سبسکرپشن پلان لوڈ نہیں ہو سکے۔ دوبارہ کوشش کریں۔",
  "We couldn't load your invoices. Please try again.": "آپ کے انوائس لوڈ نہیں ہو سکے۔ دوبارہ کوشش کریں۔",
  "We couldn't load your refund requests. Please try again.": "رقم واپسی درخواستیں لوڈ نہیں ہو سکیں۔ دوبارہ کوشش کریں۔",
  "We couldn't load your withdrawal requests. Please try again.": "رقم نکلوانے کی درخواستیں لوڈ نہیں ہو سکیں۔ دوبارہ کوشش کریں۔",
  "We couldn't read that photo. Please choose another one.": "یہ تصویر پڑھی نہیں جا سکی۔ دوسری تصویر منتخب کریں۔",
  "We couldn't submit this payment. Please try again.": "ادائیگی جمع نہیں ہو سکی۔ دوبارہ کوشش کریں۔",
  "We couldn't submit your refund request. Please try again.": "رقم واپسی درخواست جمع نہیں ہو سکی۔ دوبارہ کوشش کریں۔",
  "We couldn't submit your subscription request. Please try again.": "سبسکرپشن درخواست جمع نہیں ہو سکی۔ دوبارہ کوشش کریں۔",
  "We couldn't submit your withdrawal request. Please try again.": "رقم نکلوانے کی درخواست جمع نہیں ہو سکی۔ دوبارہ کوشش کریں۔",
  "We couldn't upload the screenshot. Please try again.": "اسکرین شاٹ اپ لوڈ نہیں ہو سکا۔ دوبارہ کوشش کریں۔",
  "Withdrawal Requests": "رقم نکلوانے کی درخواستیں",
  "You already have a pending withdrawal request. Please wait for it to be reviewed.": "آپ کی ایک درخواست پہلے ہی زیر التوا ہے۔ جائزے کا انتظار کریں۔",
  "Your commission payment is under review. You'll be notified once approved.": "آپ کی کمیشن ادائیگی زیر جائزہ ہے۔ منظوری پر اطلاع دی جائے گی۔",
  "Your invoice was saved and is ready to share.": "آپ کا انوائس محفوظ ہو گیا ہے اور شیئر کرنے کے لیے تیار ہے۔",
  "Your subscription has been cancelled.": "آپ کی سبسکرپشن منسوخ ہو گئی ہے۔",
  "Your subscription request is pending admin approval.": "آپ کی سبسکرپشن درخواست ایڈمن منظوری کی منتظر ہے۔",
  "Your withdrawal request has been submitted for review.": "آپ کی رقم نکلوانے کی درخواست جائزے کے لیے جمع ہو گئی ہے۔",
  "Yearly": "سالانہ",
  "Something went wrong. Please try again.": "کچھ غلط ہو گیا۔ دوبارہ کوشش کریں۔",
  "No internet connection. Please check your network and try again.": "انٹرنیٹ کنکشن نہیں ہے۔ نیٹ ورک چیک کر کے دوبارہ کوشش کریں۔",
  "The request took too long. Please check your connection and try again.": "درخواست میں زیادہ وقت لگا۔ کنکشن چیک کر کے دوبارہ کوشش کریں۔",
  "Athoo is temporarily unavailable. Please try again shortly.": "Athoo عارضی طور پر دستیاب نہیں۔ تھوڑی دیر بعد کوشش کریں۔",

  // RC2 Phase 8B3B — finance, icon and professional UX
  "Your commission account is clear. Keep completing jobs!": "آپ کا کمیشن اکاؤنٹ صاف ہے۔ کام مکمل کرتے رہیں!",
  "Transfer your dues to one of the Athoo accounts below, then fill in the details and attach your payment screenshot. Your account will be unblocked once the payment is approved.": "اپنی واجب الادا رقم نیچے دیے گئے اتھو اکاؤنٹ میں منتقل کریں، تفصیلات درج کریں اور ادائیگی کا اسکرین شاٹ منسلک کریں۔ منظوری کے بعد آپ کا اکاؤنٹ بحال ہو جائے گا۔",
  "No payment accounts are available right now. Please contact Athoo Support for payment instructions.": "اس وقت ادائیگی کا کوئی اکاؤنٹ دستیاب نہیں۔ براہ کرم ادائیگی کی ہدایات کے لیے اتھو سپورٹ سے رابطہ کریں۔",
  "Account Title": "اکاؤنٹ کا عنوان",
  "Account Number": "اکاؤنٹ نمبر",
  "IBAN": "آئی بین",
  "Amount Paid (PKR)": "ادا کی گئی رقم (روپے)",
  "Maximum {{amount}}": "زیادہ سے زیادہ {{amount}}",
  "Pay full dues ({{amount}})": "مکمل واجبات ادا کریں ({{amount}})",
  "Transaction Reference / TID": "ٹرانزیکشن ریفرنس / TID",
  "e.g. TXN123456789": "مثلاً TXN123456789",
  "required": "ضروری",
  "optional": "اختیاری",
  "Note": "نوٹ",
  "Any additional details about this payment…": "اس ادائیگی کے بارے میں مزید تفصیلات…",
  "Submitting…": "جمع ہو رہا ہے…",
  "Submit Payment for Review": "جائزے کے لیے ادائیگی جمع کریں",
  "Reference": "ریفرنس",
  "No eligible bookings. Only completed or cancelled bookings can be refunded.": "کوئی اہل بکنگ نہیں۔ صرف مکمل یا منسوخ بکنگ کے لیے رقم واپسی مانگی جا سکتی ہے۔",
  "Approved refunds are normally processed within 3–5 business days. We will notify you when your request is reviewed.": "منظور شدہ رقم واپسی عام طور پر 3 سے 5 کاروباری دنوں میں مکمل ہوتی ہے۔ درخواست کے جائزے کے بعد ہم آپ کو اطلاع دیں گے۔",
  "Submit a refund request if you have an issue with a completed booking.": "اگر مکمل بکنگ میں مسئلہ ہو تو رقم واپسی کی درخواست جمع کریں۔",
  "Pending Review": "جائزے کا منتظر",
  "Approved": "منظور شدہ",
  "Declined": "مسترد",
  "Refund Paid": "رقم واپس کر دی گئی",
  "Minimum Rs. 500": "کم از کم 500 روپے",
  "e.g. Muhammad Ali": "مثلاً محمد علی",
  "Account number or mobile wallet number": "اکاؤنٹ نمبر یا موبائل والٹ نمبر",
  "e.g. Meezan Bank, EasyPaisa, JazzCash": "مثلاً میزان بینک، ایزی پیسہ، جاز کیش",
  "Any additional information for the admin": "ایڈمن کے لیے کوئی اضافی معلومات",
  "Submit your first withdrawal request above.": "اپنی پہلی رقم نکلوانے کی درخواست اوپر جمع کریں۔",
  "Paid": "ادا شدہ",
  "Close": "بند کریں",
  "Priority booking support": "ترجیحی بکنگ سپورٹ",
  "Verified customer badge": "تصدیق شدہ کسٹمر بیج",
  "Exclusive promo codes": "خصوصی پرومو کوڈز",
  "Faster response from providers": "سروس فراہم کنندگان سے تیز جواب",
  "Unlock exclusive benefits and priority services for every booking in Pakistan.": "پاکستان میں ہر بکنگ کے لیے خصوصی فوائد اور ترجیحی خدمات حاصل کریں۔",
  "Your payment is being reviewed. We will notify you after approval.": "آپ کی ادائیگی کا جائزہ لیا جا رہا ہے۔ منظوری کے بعد ہم آپ کو اطلاع دیں گے۔",
  "20% off": "20٪ رعایت",
  "Save 20%": "20٪ بچت",
  "Subscribe for {{amount}}/{{period}}": "{{amount}} فی {{period}} سبسکرائب کریں",
  "month": "ماہ",
  "year": "سال",
  "monthly": "ماہانہ",
  "yearly": "سالانہ",
  "active": "فعال",
  "expired": "میعاد ختم",
  "cancelled": "منسوخ",
  "rejected": "مسترد",
  "cancellation scheduled": "منسوخی طے شدہ",
  "After subscribing, send payment through the available payment method and enter the transaction ID. Athoo will notify you after review.": "سبسکرائب کرنے کے بعد دستیاب طریقے سے ادائیگی کریں اور ٹرانزیکشن آئی ڈی درج کریں۔ جائزے کے بعد اتھو آپ کو اطلاع دے گا۔",
  "Subscribe": "سبسکرائب کریں",
  "1. Send payment using the available Athoo payment details.": "1۔ اتھو کی دستیاب ادائیگی کی تفصیلات استعمال کر کے رقم بھیجیں۔",
  "2. Copy the transaction or reference ID.": "2۔ ٹرانزیکشن یا ریفرنس آئی ڈی کاپی کریں۔",
  "3. Enter it below, attach the screenshot, and submit.": "3۔ اسے نیچے درج کریں، اسکرین شاٹ منسلک کریں اور جمع کریں۔",
  "e.g. EP1234567890": "مثلاً EP1234567890",

  // RC2 Phase 8B3B — localized invoice documents
  "Home Services · Across Pakistan": "گھریلو سروسز · پورے پاکستان میں",
  "Home Services · Pakistan": "گھریلو سروسز · پاکستان",
  "Billed To": "بل برائے",
  "Service By": "سروس فراہم کنندہ",
  "Final Invoice = Hourly Rate × Actual Job Time + Travel Charges": "حتمی انوائس = فی گھنٹہ شرح × اصل کام کا وقت + سفری چارجز",
  "Hourly Rate": "فی گھنٹہ شرح",
  "hour": "گھنٹہ",
  "hour(s)": "گھنٹے",
  "Travel Charges": "سفری چارجز",
  "Separate from hourly rate": "فی گھنٹہ شرح سے الگ",
  "Discount Applied": "رعایت لاگو",
  "Payment was made directly to the service provider. Athoo does not handle funds. This is an electronic receipt only.": "ادائیگی براہ راست سروس فراہم کنندہ کو کی گئی۔ اتھو رقم وصول نہیں کرتا۔ یہ صرف الیکٹرانک رسید ہے۔",
  "Provider Earnings Statement": "سروس فراہم کنندہ کی آمدنی کا بیان",
  "EARNED": "کمائی",
  "Service Provided To": "سروس فراہم کی گئی برائے",
  "TOTAL EARNED": "کل کمائی",
  "This earnings statement reflects what you received directly from the customer. Keep it for your records.": "یہ آمدنی کا بیان وہ رقم ظاہر کرتا ہے جو آپ نے براہ راست کسٹمر سے وصول کی۔ اسے اپنے ریکارڈ کے لیے محفوظ رکھیں۔",
  "A visit/call-out charge of {{amount}} was applied for this job.": "اس کام کے لیے {{amount}} وزٹ / کال آؤٹ چارج لاگو ہوا۔",
  "Invoices will appear here after completing your first job.": "پہلا کام مکمل ہونے کے بعد انوائس یہاں نظر آئیں گے۔",

  // RC2 Phase 8B3B — dynamic payment accounts
  "Payment account unavailable": "ادائیگی کا اکاؤنٹ دستیاب نہیں",
  "No Athoo payment account is available right now. Please contact Athoo Support before paying.": "اس وقت اتھو کا کوئی ادائیگی اکاؤنٹ دستیاب نہیں۔ رقم بھیجنے سے پہلے اتھو سپورٹ سے رابطہ کریں۔",
  "Athoo Payment Accounts": "اتھو ادائیگی اکاؤنٹس",
  "After paying, enter the transaction or reference ID and attach the payment screenshot.": "ادائیگی کے بعد ٹرانزیکشن یا ریفرنس آئی ڈی درج کریں اور ادائیگی کا اسکرین شاٹ منسلک کریں۔",
  "No payment is required for this plan.": "اس پلان کے لیے ادائیگی ضروری نہیں۔",
  "After subscribing, use one of the active Athoo payment accounts and enter the transaction ID. We will notify you after review.": "سبسکرائب کرنے کے بعد اتھو کے فعال ادائیگی اکاؤنٹس میں سے ایک استعمال کریں اور ٹرانزیکشن آئی ڈی درج کریں۔ جائزے کے بعد ہم آپ کو اطلاع دیں گے۔",
  "Subscribe to {{plan}}": "{{plan}} کو سبسکرائب کریں",

  // RC2 Phase 8B4 — support, security, policies, notification center, and professional UX
  "Contact Support": "سپورٹ سے رابطہ",
  "View active support tickets": "فعال سپورٹ ٹکٹ دیکھیں",
  "Ticket submitted": "ٹکٹ جمع ہو گیا",
  "Our support team will review your request and reply in your support tickets.": "ہماری سپورٹ ٹیم آپ کی درخواست کا جائزہ لے گی اور آپ کے سپورٹ ٹکٹ میں جواب دے گی۔",
  "View my tickets": "میرے ٹکٹ دیکھیں",
  "Back to help": "مدد پر واپس جائیں",
  "Describe the problem clearly. You can attach up to five screenshots or short videos.": "مسئلہ واضح طور پر بیان کریں۔ آپ پانچ تک اسکرین شاٹس یا مختصر ویڈیوز منسلک کر سکتے ہیں۔",
  "What's the issue about?": "مسئلہ کس بارے میں ہے؟",
  "Booking issue": "بکنگ کا مسئلہ",
  "Payment problem": "ادائیگی کا مسئلہ",
  "Customer complaint": "کسٹمر کی شکایت",
  "Provider complaint": "فراہم کنندہ کی شکایت",
  "App technical issue": "ایپ کا تکنیکی مسئلہ",
  "Account access": "اکاؤنٹ تک رسائی",
  "Refund request": "رقم واپسی کی درخواست",
  "Other": "دیگر",
  "Attach screenshots or video proof (optional)": "اسکرین شاٹ یا ویڈیو ثبوت منسلک کریں (اختیاری)",
  "Add proof": "ثبوت شامل کریں",
  "Take a photo or video, or choose existing media from your gallery.": "تصویر یا ویڈیو بنائیں، یا گیلری سے موجود میڈیا منتخب کریں۔",
  "Add proof from camera or gallery": "کیمرہ یا گیلری سے ثبوت شامل کریں",
  "{{count}} of 5 files selected": "5 میں سے {{count}} فائلیں منتخب",
  "Video proof": "ویڈیو ثبوت",
  "Screenshot proof": "اسکرین شاٹ ثبوت",
  "Remove attachment": "منسلک فائل ہٹائیں",
  "Describe your issue": "اپنا مسئلہ بیان کریں",
  "Tell us what happened, what you expected, and any important details.": "بتائیں کیا ہوا، آپ کیا توقع کر رہے تھے، اور اہم تفصیلات کیا ہیں۔",
  "{{count}} / 500 characters": "{{count}} / 500 حروف",
  "Please describe your issue in at least 20 characters.": "براہ کرم اپنا مسئلہ کم از کم 20 حروف میں بیان کریں۔",
  "We couldn't submit your request. Please try again.": "ہم آپ کی درخواست جمع نہیں کر سکے۔ دوبارہ کوشش کریں۔",
  "Submit support request": "سپورٹ درخواست جمع کریں",
  "Please keep Athoo open while attachments are uploading.": "منسلک فائلیں اپ لوڈ ہونے تک اتھو کھلا رکھیں۔",
  "Most requests receive a response within 24 hours.": "زیادہ تر درخواستوں کا جواب 24 گھنٹوں کے اندر ملتا ہے۔",
  "My support tickets": "میرے سپورٹ ٹکٹ",
  "{{count}} support ticket(s)": "{{count}} سپورٹ ٹکٹ",
  "Create a new support ticket": "نیا سپورٹ ٹکٹ بنائیں",
  "Loading support tickets…": "سپورٹ ٹکٹ لوڈ ہو رہے ہیں…",
  "Unable to load tickets": "ٹکٹ لوڈ نہیں ہو سکے",
  "We couldn't load your support tickets. Please try again.": "ہم آپ کے سپورٹ ٹکٹ لوڈ نہیں کر سکے۔ دوبارہ کوشش کریں۔",
  "Try again": "دوبارہ کوشش کریں",
  "No support tickets yet": "ابھی کوئی سپورٹ ٹکٹ نہیں",
  "Create a support request and you can track every reply here.": "سپورٹ درخواست بنائیں اور ہر جواب یہاں ٹریک کریں۔",
  "Contact support": "سپورٹ سے رابطہ",
  "Support ticket": "سپورٹ ٹکٹ",
  "In progress": "جاری ہے",
  "Resolved": "حل شدہ",
  "Closed": "بند",
  "Open": "کھلا",
  "You": "آپ",
  "Loading support replies": "سپورٹ جوابات لوڈ ہو رہے ہیں",
  "Loading replies…": "جوابات لوڈ ہو رہے ہیں…",
  "We couldn't load this conversation. Please try again.": "ہم یہ گفتگو لوڈ نہیں کر سکے۔ دوبارہ کوشش کریں۔",
  "Awaiting support response": "سپورٹ کے جواب کا انتظار",
  "We will notify you when the support team replies.": "سپورٹ ٹیم کے جواب پر ہم آپ کو اطلاع دیں گے۔",
  "Support team": "سپورٹ ٹیم",
  "Notifications": "اطلاعات",
  "{{count}} unread": "{{count}} غیر پڑھی",
  "You're all caught up": "آپ سب دیکھ چکے ہیں",
  "Notification options": "اطلاعات کے اختیارات",
  "Clear notifications": "اطلاعات صاف کریں",
  "Remove all notifications from this device?": "اس ڈیوائس سے تمام اطلاعات ہٹا دیں؟",
  "Clear all": "سب صاف کریں",
  "No notifications": "کوئی اطلاع نہیں",
  "Booking updates, messages, payments, and support replies will appear here.": "بکنگ اپ ڈیٹس، پیغامات، ادائیگیاں اور سپورٹ جوابات یہاں نظر آئیں گے۔",
  "Mark all notifications as read": "تمام اطلاعات کو پڑھا ہوا نشان زد کریں",
  "Mark all as read": "سب کو پڑھا ہوا نشان زد کریں",
  "Just now": "ابھی",
  "{{count}} min ago": "{{count}} منٹ پہلے",
  "{{count}} hr ago": "{{count}} گھنٹے پہلے",
  "{{count}} day(s) ago": "{{count}} دن پہلے",
  "Dismiss {{title}}": "{{title}} ہٹائیں",
  "Account security": "اکاؤنٹ سیکیورٹی",
  "Protect your account": "اپنا اکاؤنٹ محفوظ رکھیں",
  "Use a unique password. Athoo will never ask you to share it in chat, calls, or support messages.": "منفرد پاس ورڈ استعمال کریں۔ اتھو کبھی چیٹ، کال یا سپورٹ پیغام میں پاس ورڈ مانگے گا نہیں۔",
  "Current password (optional if none is set)": "موجودہ پاس ورڈ (اگر مقرر نہیں تو اختیاری)",
  "Enter current password": "موجودہ پاس ورڈ درج کریں",
  "New password": "نیا پاس ورڈ",
  "At least 8 characters": "کم از کم 8 حروف",
  "Enter the new password again": "نیا پاس ورڈ دوبارہ درج کریں",
  "Hide password": "پاس ورڈ چھپائیں",
  "Show password": "پاس ورڈ دکھائیں",
  "Passwords do not match.": "پاس ورڈ ایک جیسے نہیں ہیں۔",
  "Password too short": "پاس ورڈ بہت مختصر ہے",
  "Passwords do not match": "پاس ورڈ ایک جیسے نہیں ہیں",
  "Please enter the same new password in both fields.": "دونوں خانوں میں ایک ہی نیا پاس ورڈ درج کریں۔",
  "Choose a different password": "مختلف پاس ورڈ منتخب کریں",
  "Your new password should be different from your current password.": "نیا پاس ورڈ موجودہ پاس ورڈ سے مختلف ہونا چاہیے۔",
  "Password updated": "پاس ورڈ اپ ڈیٹ ہو گیا",
  "Your password has been saved securely. You can continue using OTP or sign in with your password.": "آپ کا پاس ورڈ محفوظ طور پر محفوظ ہو گیا۔ آپ OTP یا پاس ورڈ سے سائن اِن کر سکتے ہیں۔",
  "Done": "مکمل",
  "Unable to update password": "پاس ورڈ اپ ڈیٹ نہیں ہو سکا",
  "We couldn't update your password. Please check your current password and try again.": "ہم پاس ورڈ اپ ڈیٹ نہیں کر سکے۔ موجودہ پاس ورڈ چیک کر کے دوبارہ کوشش کریں۔",
  "Saving…": "محفوظ کیا جا رہا ہے…",
  "Save password": "پاس ورڈ محفوظ کریں",
  "Forgot password? Reset with OTP": "پاس ورڈ بھول گئے؟ OTP سے ری سیٹ کریں",
  "Strong password checklist": "مضبوط پاس ورڈ چیک لسٹ",
  "Use at least 8 characters": "کم از کم 8 حروف استعمال کریں",
  "Mix letters, numbers, and symbols": "حروف، اعداد اور علامات ملائیں",
  "Do not reuse a password from another account": "دوسرے اکاؤنٹ کا پاس ورڈ دوبارہ استعمال نہ کریں",
  "Never share your password or OTP": "پاس ورڈ یا OTP کبھی شیئر نہ کریں",
  "Help & FAQs": "مدد اور عام سوالات",
  "Provider support centre": "فراہم کنندہ سپورٹ مرکز",
  "How can we help?": "ہم کیسے مدد کر سکتے ہیں؟",
  "Find answers about jobs, earnings, commission, verification, and your provider account.": "کام، آمدنی، کمیشن، تصدیق اور فراہم کنندہ اکاؤنٹ کے بارے میں جوابات تلاش کریں۔",
  "Find answers about bookings, providers, payments, refunds, and your customer account.": "بکنگ، فراہم کنندگان، ادائیگی، رقم واپسی اور کسٹمر اکاؤنٹ کے بارے میں جوابات تلاش کریں۔",
  "My tickets": "میرے ٹکٹ",
  "Frequently asked questions": "اکثر پوچھے گئے سوالات",
  "{{count}} article(s)": "{{count}} مضامین",
  "Loading help articles…": "مدد کے مضامین لوڈ ہو رہے ہیں…",
  "Unable to load help articles": "مدد کے مضامین لوڈ نہیں ہو سکے",
  "We couldn't refresh help articles. Please try again.": "ہم مدد کے مضامین تازہ نہیں کر سکے۔ دوبارہ کوشش کریں۔",
  "No help articles are available right now": "اس وقت مدد کا کوئی مضمون دستیاب نہیں",
  "Please contact support and we will help you directly.": "سپورٹ سے رابطہ کریں، ہم براہ راست مدد کریں گے۔",
  "Showing saved help articles. Pull-to-refresh is unavailable until your connection returns.": "محفوظ مدد مضامین دکھائے جا رہے ہیں۔ کنکشن بحال ہونے تک تازہ کاری دستیاب نہیں۔",
  "Tap again to collapse": "بند کرنے کے لیے دوبارہ ٹیپ کریں",
  "Privacy & security": "رازداری و سیکیورٹی",
  "Phone number protection": "فون نمبر کا تحفظ",
  "Athoo keeps personal phone numbers out of public profiles and uses in-app communication for service conversations.": "اتھو ذاتی فون نمبر عوامی پروفائل سے چھپاتا ہے اور سروس گفتگو کے لیے ایپ کے اندر رابطہ استعمال کرتا ہے۔",
  "Document protection": "دستاویزات کا تحفظ",
  "Verified provider information": "تصدیق شدہ فراہم کنندہ معلومات",
  "Identity and verification documents are private and are used only for verification, safety, and lawful platform operations.": "شناختی اور تصدیقی دستاویزات نجی ہیں اور صرف تصدیق، حفاظت اور قانونی پلیٹ فارم آپریشن کے لیے استعمال ہوتی ہیں۔",
  "Customers see verification status, not a provider's private identity documents.": "کسٹمر تصدیقی حیثیت دیکھتے ہیں، فراہم کنندہ کی نجی شناختی دستاویزات نہیں۔",
  "Location controls": "لوکیشن کنٹرولز",
  "Precise location is used only when needed for service discovery, booking, arrival, and active-job safety features.": "درست لوکیشن صرف سروس تلاش، بکنگ، آمد اور فعال کام کے حفاظتی فیچرز کے لیے ضرورت کے وقت استعمال ہوتی ہے۔",
  "Responsible data handling": "ذمہ دارانہ ڈیٹا ہینڈلنگ",
  "Athoo limits data access to authorized operations and does not display storage, database, or internal system details to other users.": "اتھو ڈیٹا تک رسائی مجاز آپریشنز تک محدود رکھتا ہے اور اسٹوریج، ڈیٹا بیس یا اندرونی نظام کی تفصیلات دوسرے صارفین کو نہیں دکھاتا۔",
  "Account controls": "اکاؤنٹ کنٹرولز",
  "You can update your password, review policies, contact support, or request permanent account deletion from the app.": "آپ پاس ورڈ اپ ڈیٹ، پالیسیاں دیکھ، سپورٹ سے رابطہ یا ایپ سے مستقل اکاؤنٹ حذف کرنے کی درخواست کر سکتے ہیں۔",
  "Your privacy is part of the product": "آپ کی رازداری پروڈکٹ کا حصہ ہے",
  "Athoo uses privacy controls across profiles, bookings, chat, location, documents, payments, and support workflows.": "اتھو پروفائل، بکنگ، چیٹ، لوکیشن، دستاویزات، ادائیگی اور سپورٹ ورک فلو میں رازداری کنٹرول استعمال کرتا ہے۔",
  "Security and policy controls": "سیکیورٹی اور پالیسی کنٹرولز",
  "Change password": "پاس ورڈ تبدیل کریں",
  "Privacy policy": "رازداری پالیسی",
  "Terms of service": "شرائطِ استعمال",
  "Danger zone": "خطرناک علاقہ",
  "Account deletion is permanent. Download or save anything you need before continuing.": "اکاؤنٹ حذف کرنا مستقل ہے۔ جاری رکھنے سے پہلے ضروری چیزیں محفوظ کر لیں۔",
  "Request account deletion": "اکاؤنٹ حذف کرنے کی درخواست",
  "Your account and eligible personal data will be permanently deleted. Records that Athoo must retain for legal, safety, fraud-prevention, or financial-audit reasons may be kept only for the required period.": "آپ کا اکاؤنٹ اور قابلِ حذف ذاتی ڈیٹا مستقل طور پر حذف ہو جائے گا۔ قانونی، حفاظتی، فراڈ روک تھام یا مالی آڈٹ کے لیے لازمی ریکارڈ صرف مطلوبہ مدت تک محفوظ رہ سکتے ہیں۔",
  "Delete account": "اکاؤنٹ حذف کریں",
  "Final confirmation": "آخری تصدیق",
  "This action cannot be undone. Do you want to continue?": "یہ عمل واپس نہیں ہو سکتا۔ کیا آپ جاری رکھنا چاہتے ہیں؟",
  "Keep my account": "میرا اکاؤنٹ رکھیں",
  "Delete permanently": "مستقل حذف کریں",
  "Deleting account…": "اکاؤنٹ حذف ہو رہا ہے…",
  "Unable to delete account": "اکاؤنٹ حذف نہیں ہو سکا",
  "We couldn't process your deletion request. Please try again or contact support.": "ہم حذف کرنے کی درخواست مکمل نہیں کر سکے۔ دوبارہ کوشش کریں یا سپورٹ سے رابطہ کریں۔",
  "About Athoo": "اتھو کے بارے میں",
  "A professional marketplace for service providers across Pakistan.": "پورے پاکستان میں سروس فراہم کنندگان کے لیے پیشہ ور مارکیٹ پلیس۔",
  "Professional home and local services across Pakistan.": "پورے پاکستان میں پیشہ ور گھریلو اور مقامی سروسز۔",
  "App version {{version}}": "ایپ ورژن {{version}}",
  "Our mission": "ہمارا مقصد",
  "Athoo connects customers and skilled service providers through structured bookings, transparent communication, privacy controls, and accountable admin operations.": "اتھو منظم بکنگ، شفاف رابطہ، رازداری کنٹرول اور جواب دہ ایڈمن آپریشن کے ذریعے کسٹمر اور ہنرمند سروس فراہم کنندگان کو ملاتا ہے۔",
  "Provider experience": "فراہم کنندہ تجربہ",
  "Customer experience": "کسٹمر تجربہ",
  "Verified marketplace": "تصدیق شدہ مارکیٹ پلیس",
  "Provider and customer workflows include identity, booking, payment-evidence, and safety controls.": "فراہم کنندہ اور کسٹمر ورک فلو میں شناخت، بکنگ، ادائیگی ثبوت اور حفاظتی کنٹرول شامل ہیں۔",
  "Transparent earnings": "شفاف آمدنی",
  "Track completed work, commission, invoices, withdrawals, and Premium requests from the provider app.": "فراہم کنندہ ایپ سے مکمل کام، کمیشن، انوائس، رقم نکلوانا اور پریمیم درخواستیں ٹریک کریں۔",
  "Private communication": "نجی رابطہ",
  "Use in-app chat, calls, notifications, and support tickets without publishing your personal phone number.": "ذاتی فون نمبر ظاہر کیے بغیر ایپ چیٹ، کال، اطلاعات اور سپورٹ ٹکٹ استعمال کریں۔",
  "Pakistan-wide service areas": "پاکستان بھر کے سروس ایریاز",
  "Manage availability, service radius, cities, and areas configured through the Athoo admin system.": "اتھو ایڈمن نظام سے مقرر دستیابی، سروس دائرہ، شہر اور علاقے منظم کریں۔",
  "Verified service providers": "تصدیق شدہ سروس فراہم کنندگان",
  "Athoo displays provider verification status and keeps private identity documents protected.": "اتھو فراہم کنندہ کی تصدیقی حیثیت دکھاتا اور نجی شناختی دستاویزات محفوظ رکھتا ہے۔",
  "Clear pricing workflows": "واضح قیمت کا طریقہ",
  "Review offers, visit charges, negotiations, invoices, and refund requests before taking action.": "کارروائی سے پہلے پیشکش، وزٹ چارج، مذاکرات، انوائس اور رقم واپسی درخواست کا جائزہ لیں۔",
  "Services across Pakistan": "پورے پاکستان میں سروسز",
  "Discover services through admin-managed categories, cities, areas, provider availability, and live booking locations.": "ایڈمن سے منظم کیٹیگریز، شہر، علاقے، فراہم کنندہ دستیابی اور لائیو بکنگ لوکیشن کے ذریعے سروسز تلاش کریں۔",
  "Contact Athoo": "اتھو سے رابطہ",
  "WhatsApp support": "واٹس ایپ سپورٹ",
  "Support email": "سپورٹ ای میل",
  "Unable to open link": "لنک نہیں کھل سکا",
  "We couldn't open {{label}} on this device. Please try again later.": "ہم اس ڈیوائس پر {{label}} نہیں کھول سکے۔ بعد میں دوبارہ کوشش کریں۔",
  "© 2026 Athoo. All rights reserved. Built for Pakistan.": "© 2026 اتھو۔ جملہ حقوق محفوظ۔ پاکستان کے لیے تیار کردہ۔",
  "Version {{version}}": "ورژن {{version}}",
  "This document explains how Athoo handles account, booking, location, document, media, finance, and support information.": "یہ دستاویز بتاتی ہے کہ اتھو اکاؤنٹ، بکنگ، لوکیشن، دستاویز، میڈیا، مالی اور سپورٹ معلومات کیسے سنبھالتا ہے۔",
  "This document explains the rules for using Athoo as a customer or independent service provider.": "یہ دستاویز کسٹمر یا آزاد سروس فراہم کنندہ کے طور پر اتھو استعمال کرنے کے قواعد بتاتی ہے۔",
  "Current policy version: {{version}}": "موجودہ پالیسی ورژن: {{version}}",
  "Service temporarily unavailable": "سروس عارضی طور پر دستیاب نہیں",
  "Athoo cannot connect right now. Please install the latest app version or contact Athoo Support.": "اتھو اس وقت رابطہ نہیں کر سکتا۔ براہ کرم ایپ کا تازہ ترین ورژن انسٹال کریں یا اتھو سپورٹ سے رابطہ کریں۔",
  "Something went wrong": "کچھ غلط ہو گیا",
  "Please try again. If the issue continues, contact Athoo Support.": "دوبارہ کوشش کریں۔ مسئلہ برقرار رہے تو اتھو سپورٹ سے رابطہ کریں۔",
  "Try Again": "دوبارہ کوشش کریں",
  "Verification code delivery is temporarily unavailable. Please try again shortly.": "تصدیقی کوڈ بھیجنے کی سہولت عارضی طور پر دستیاب نہیں۔ کچھ دیر بعد دوبارہ کوشش کریں۔",
  "Reset request is invalid or expired. Please start again.": "پاس ورڈ ری سیٹ درخواست غلط ہے یا اس کی مدت ختم ہو چکی ہے۔ دوبارہ شروع کریں۔",

};

export type Strings = typeof EN;

interface LangContextType {
  lang: Lang;
  t: Strings;
  setLang: (l: Lang) => Promise<void>;
  isUrdu: boolean;
  ready: boolean;
  direction: "ltr" | "rtl";
  textAlign: "left" | "right";
  writingDirection: "ltr" | "rtl";
  formatNumber: (value: number) => string;
  formatCurrency: (value: number) => string;
  formatDate: (value: Date | string | number) => string;
  translate: (message: string, params?: Record<string, string | number>) => string;
}

const LangContext = createContext<LangContextType | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>("en");
  const [ready, setReady] = useState(false);

  useEffect(() => {
    AsyncStorage.getItem("athoo_lang")
      .then((value) => {
        if (value === "en" || value === "ur") setLangState(value);
      })
      .catch(() => undefined)
      .finally(() => setReady(true));
  }, []);

  const setLang = useCallback(async (nextLang: Lang) => {
    setLangState(nextLang);
    try {
      await AsyncStorage.setItem("athoo_lang", nextLang);
    } catch {
      // The language still changes for the current session when local storage
      // is temporarily unavailable.
    }
  }, []);

  const value = useMemo<LangContextType>(() => {
    const isUrdu = lang === "ur";
    const locale = isUrdu ? "ur-PK" : "en-PK";
    return {
      lang,
      t: isUrdu ? UR : EN,
      setLang,
      isUrdu,
      ready,
      direction: isUrdu ? "rtl" : "ltr",
      textAlign: isUrdu ? "right" : "left",
      writingDirection: isUrdu ? "rtl" : "ltr",
      formatNumber: (value) => Number(value || 0).toLocaleString(locale),
      formatCurrency: (value) => `Rs. ${Math.max(0, Number(value || 0)).toLocaleString(locale)}`,
      formatDate: (value) => new Date(value).toLocaleDateString(locale, {
        year: "numeric",
        month: "short",
        day: "numeric",
      }),
      translate: (message, params = {}) => {
        const template = isUrdu ? (UR_MESSAGES[message] ?? message) : message;
        return template.replace(/\{\{(\w+)\}\}/g, (_match, key: string) =>
          Object.prototype.hasOwnProperty.call(params, key) ? String(params[key]) : `{{${key}}}`
        );
      },
    };
  }, [lang, ready, setLang]);

  return <LangContext.Provider value={value}>{children}</LangContext.Provider>;
}

export function useLang() {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error("useLang must be used within LanguageProvider");
  return ctx;
}

export function useOptionalLang() {
  return useContext(LangContext);
}

