Foreground true
User clamav
TCPSocket 3310
TCPAddr 127.0.0.1
DatabaseDirectory /var/lib/clamav
MaxFileSize 220M
MaxScanSize 220M
StreamMaxLength 220M
ReadTimeout 180
CommandReadTimeout 180
SendBufTimeout 180
LogTime true
LogClean false
LogSyslog false