import { useMemo, useState } from "react";
import type { LucideIcon } from "lucide-react";
import {   Accessibility, Activity, Ambulance, Anchor, Apple, Archive, Armchair, Award, Baby, Banknote, Bath, Battery, Bed, Bell, Bike, Book, BookMarked, Briefcase, BriefcaseBusiness, Brush, Bug, Building, Bus, Calculator, Calendar, Camera, Car, Circle, Clipboard, ClipboardList, Clock, Cloud, Code, Coffee, Coins, Command, Compass, Computer, Construction, Contact, Copy, Crop, Crosshair, Crown, Database, Delete, Dessert, Disc, Divide, Dock, Download, Drill, Droplets, Dumbbell, Ear, Egg, Equal, Eraser, Euro, Expand, Eye, Factory, Fan, Feather, Fence, Figma, File, Film, Fish, Flag, Flame, Flashlight, Flower, Flower2, Focus, Folder, Forklift, Forward, Frame, Frown, Fuel, Gamepad, Gauge, Gem, Ghost, Gift, Github, Gitlab, Globe, Grid3x3, Hammer, Hash, Headphones, Headset, Heart, Hexagon, Highlighter, History, Hop, Hospital, Hotel, Hourglass, House, Image, Inbox, Key, Keyboard, Lamp, Landmark, Languages, Laptop, Leaf, Library, Lightbulb, Link, List, Loader, Lock, Luggage, Magnet, Mail, Mailbox, Map, Maximize, Medal, Megaphone, Menu, Mic, Microwave, Milestone, Minimize, Minus, Monitor, Moon, Move, Music, Navigation, Newspaper, Notebook, Nut, Octagon, Option, Orbit, Package, Paintbrush, Palette, Pause, Pencil, Pentagon, Percent, Phone, Pi, Piano, Pickaxe, Pill, Pin, Pizza, Plane, Play, Plug, Plus, Pocket, Pointer, Popcorn, Power, Presentation, Printer, Projector, Proportions, Puzzle, Pyramid, Quote, Radio, Receipt, Recycle, Redo, Refrigerator, Regex, Repeat, Reply, Rewind, Ribbon, Rocket, Route, Rows2, Rss, Ruler, Sailboat, Save, Scale, Scan, School, Scissors, Search, Section, Send, Server, Settings, Settings2, Share, Shield, Ship, Shirt, Shovel, Shrink, Shuffle, Sigma, Signpost, Slash, Slice, SlidersHorizontal, Smartphone, Smile, Snail, Snowflake, Sofa, Space, Sparkle, Sparkles, Speaker, Speech, Square, Star, Stethoscope, Sticker, Store, Strikethrough, Subscript, Sun, Superscript, Sword, Syringe, Table, Tag, Tags, Target, Tent, Terminal, Thermometer, Ticket, Timer, Toilet, Tornado, Touchpad, Tractor, Trash, Trash2, Trees, Trophy, Truck, Turtle, Tv, Type, Umbrella, University, Unlink, Unplug, Upload, User, Users, Utensils, Variable, Vault, Vibrate, Video, View, Voicemail, Volume, Vote, Wallet, Wand, Warehouse, Watch, Waves, Webcam, Webhook, Weight, Wheat, Wifi, Wind, Wine, Wrench, X, Youtube, Zap
} from "lucide-react"

export type IconOption = { name: string; label: string; icon: LucideIcon; keywords: string[] };

const icon = (name: string, label: string, glyph: LucideIcon, keywords: string[] = []): IconOption => ({ name, label, icon: glyph, keywords });

export const ADMIN_ICON_OPTIONS: IconOption[] = [
  icon("accessibility", "Accessibility", Accessibility, ["care", "support"]),
  icon("accessibility", "Accessibility", Accessibility, ["disability", "wheelchair", "access"]),
  icon("activity", "Activity", Activity, ["health", "vital", "pulse"]),
  icon("ambulance", "Ambulance", Ambulance, ["emergency", "health"]),
  icon("ambulance", "Ambulance", Ambulance, ["emergency", "medical", "health"]),
  icon("anchor", "Anchor", Anchor, ["sea", "shipping", "maritime"]),
  icon("apple", "Food", Apple, ["food", "nutrition"]),
  icon("archive", "Archive", Archive, ["storage", "records"]),
  icon("armchair", "Armchair", Armchair, ["furniture", "home"]),
  icon("award", "Award", Award, ["quality", "top"]),
  icon("award", "Award", Award, ["achievement", "badge", "prize"]),
  icon("baby", "Baby", Baby, ["child", "infant", "nursery"]),
  icon("banknote", "Cash", Banknote, ["payment", "finance"]),
  icon("bath", "Bath", Bath, ["bathroom", "plumber"]),
  icon("battery", "Battery", Battery, ["power", "charge", "energy"]),
  icon("bed", "Bed", Bed, ["furniture", "home"]),
  icon("bell", "Bell", Bell, ["notification", "alert"]),
  icon("bell", "Bell", Bell, ["notification", "alert", "bell"]),
  icon("bike", "Bike", Bike, ["vehicle", "cycling", "transport"]),
  icon("bike", "Bike", Bike, ["vehicle", "delivery"]),
  icon("book", "Book", Book, ["read", "learn", "library"]),
  icon("bookmark", "Bookmark", BookMarked, ["save", "favorite", "mark"]),
  icon("briefcase", "Briefcase", Briefcase, ["business", "work", "professional"]),
  icon("briefcase", "Business", BriefcaseBusiness, ["office", "professional"]),
  icon("brush", "Brush", Brush, ["paint", "clean", "art"]),
  icon("brush", "Brush", Brush, ["cleaner", "cleaning"]),
  icon("bug", "Bug", Bug, ["insect", "error", "debug"]),
  icon("building", "Building", Building, ["office", "structure"]),
  icon("building", "Building", Building, ["office", "property"]),
  icon("bus", "Bus", Bus, ["transport", "vehicle"]),
  icon("bus", "Bus", Bus, ["transport", "vehicle", "travel"]),
  icon("calculator", "Calculator", Calculator, ["math", "compute", "calculate"]),
  icon("calendar", "Calendar", Calendar, ["date", "schedule", "time"]),
  icon("camera", "Camera", Camera, ["photo", "media"]),
  icon("camera", "Camera", Camera, ["photo", "image", "capture"]),
  icon("car", "Car", Car, ["vehicle", "mechanic"]),
  icon("car", "Car", Car, ["vehicle", "automobile", "transport"]),
  icon("circle", "Circle", Circle, ["shape", "round", "dot"]),
  icon("clipboard", "Clipboard", Clipboard, ["document", "notes", "list"]),
  icon("clock", "Clock", Clock, ["time", "schedule"]),
  icon("clock", "Clock", Clock, ["time", "schedule", "hour"]),
  icon("cloud", "Cloud", Cloud, ["weather", "online"]),
  icon("cloud", "Cloud", Cloud, ["weather", "online", "storage"]),
  icon("code", "Code", Code, ["programming", "terminal", "script"]),
  icon("coffee", "Coffee", Coffee, ["cafe", "beverage"]),
  icon("coffee", "Coffee", Coffee, ["beverage", "cafe", "drink"]),
  icon("coins", "Coins", Coins, ["money", "currency", "payment"]),
  icon("command", "Command", Command, ["terminal", "keyboard", "shortcut"]),
  icon("compass", "Compass", Compass, ["navigation", "direction", "locate"]),
  icon("computer", "Computer", Computer, ["desktop", "laptop", "tech"]),
  icon("construction", "Construction", Construction, ["building", "road"]),
  icon("contact", "Contact", Contact, ["phone", "people", "communication"]),
  icon("copy", "Copy", Copy, ["duplicate", "clone", "copy"]),
  icon("crop", "Crop", Crop, ["image", "photo", "resize"]),
  icon("crosshair", "Crosshair", Crosshair, ["target", "aim", "precision"]),
  icon("crown", "Crown", Crown, ["premium", "vip", "king"]),
  icon("crown", "Premium", Crown, ["premium", "vip"]),
  icon("database", "Database", Database, ["data", "storage", "server"]),
  icon("delete", "Delete", Delete, ["remove", "trash", "erase"]),
  icon("dessert", "Dessert", Dessert, ["sweet", "cake", "food"]),
  icon("disc", "Disc", Disc, ["music", "cd", "disk"]),
  icon("divide", "Divide", Divide, ["math", "calculation"]),
  icon("dock", "Dock", Dock, ["panel", "launchpad", "apps"]),
  icon("download", "Download", Download, ["save", "export", "get"]),
  icon("drill", "Drill", Drill, ["hardware", "repair"]),
  icon("droplets", "Droplets", Droplets, ["water", "plumber"]),
  icon("droplets", "Droplets", Droplets, ["water", "liquid", "drip"]),
  icon("dumbbell", "Fitness", Dumbbell, ["gym", "trainer"]),
  icon("dumbbell", "Dumbbell", Dumbbell, ["fitness", "gym", "exercise"]),
  icon("ear", "Ear", Ear, ["hearing", "audio", "sound"]),
  icon("egg", "Egg", Egg, ["food", "chicken", "farm"]),
  icon("equal", "Equal", Equal, ["math", "equal"]),
  icon("eraser", "Eraser", Eraser, ["erase", "remove", "write"]),
  icon("euro", "Euro", Euro, ["money", "currency", "europe"]),
  icon("expand", "Expand", Expand, ["enlarge", "maximize", "bigger"]),
  icon("eye", "Eye", Eye, ["view", "see", "visible"]),
  icon("factory", "Factory", Factory, ["industry", "manufacturing", "production"]),
  icon("fan", "Fan", Fan, ["wind", "cooling", "ac"]),
  icon("fan", "Fan", Fan, ["ac", "cooling"]),
  icon("feather", "Feather", Feather, ["light", "write", "pen"]),
  icon("fence", "Fence", Fence, ["yard", "property", "boundary"]),
  icon("figma", "Figma", Figma, ["design", "mockup", "ui"]),
  icon("file", "File", File, ["document", "page", "paper"]),
  icon("film", "Film", Film, ["movie", "cinema", "video"]),
  icon("fish", "Fish", Fish, ["sea", "animal", "aquatic"]),
  icon("flag", "Flag", Flag, ["marker", "location", "mark"]),
  icon("flame", "Flame", Flame, ["fire", "heat", "hot"]),
  icon("flame", "Flame", Flame, ["gas", "heater"]),
  icon("flashlight", "Flashlight", Flashlight, ["light", "lamp", "bright"]),
  icon("flower", "Flower", Flower2, ["garden", "decor"]),
  icon("flower", "Flower", Flower, ["plant", "nature", "garden"]),
  icon("focus", "Focus", Focus, ["camera", "target", "sharp"]),
  icon("folder", "Folder", Folder, ["directory", "files", "folder"]),
  icon("forklift", "Forklift", Forklift, ["lift", "warehouse", "heavy"]),
  icon("forward", "Forward", Forward, ["skip", "next", "media"]),
  icon("frame", "Frame", Frame, ["border", "picture", "photo"]),
  icon("frown", "Frown", Frown, ["sad", "unhappy", "emotion"]),
  icon("fuel", "Fuel", Fuel, ["gas", "petrol", "energy"]),
  icon("gamepad", "Gamepad", Gamepad, ["controller", "gaming", "play"]),
  icon("gauge", "Gauge", Gauge, ["speed", "meter", "measure"]),
  icon("gem", "Gem", Gem, ["jewel", "diamond", "precious"]),
  icon("ghost", "Ghost", Ghost, ["spooky", "holiday", "halloween"]),
  icon("gift", "Gift", Gift, ["promotion", "reward"]),
  icon("gift", "Gift", Gift, ["present", "surprise", "reward"]),
  icon("github", "GitHub", Github, ["git", "github", "code"]),
  icon("gitlab", "GitLab", Gitlab, ["git", "gitlab", "code"]),
  icon("globe", "Globe", Globe, ["world", "earth", "international"]),
  icon("grid", "Grid", Grid3x3, ["layout", "table", "matrix"]),
  icon("hammer", "Hammer", Hammer, ["carpenter", "construction"]),
  icon("hash", "Hash", Hash, ["number", "symbol", "pound"]),
  icon("headphones", "Headphones", Headphones, ["audio", "music", "sound"]),
  icon("headphones", "Support", Headphones, ["help"]),
  icon("headset", "Headset", Headset, ["audio", "voice", "call"]),
  icon("heart", "Heart", Heart, ["love", "favorite", "like"]),
  icon("heart", "Heart", Heart, ["favorite", "care"]),
  icon("hexagon", "Hexagon", Hexagon, ["shape", "honeycomb", "geometry"]),
  icon("highlighter", "Highlighter", Highlighter, ["mark", "highlight", "pen"]),
  icon("history", "History", History, ["timeline", "past", "records"]),
  icon("home", "Home", House, ["house", "main", "house"]),
  icon("home", "Home", House, ["house", "property"]),
  icon("hop", "Hop", Hop, ["transport", "vehicle", "travel"]),
  icon("hospital", "Hospital", Hospital, ["health", "medical"]),
  icon("hospital", "Hospital", Hospital, ["medical", "health", "care"]),
  icon("hotel", "Hotel", Hotel, ["accommodation", "stay", "lodging"]),
  icon("hourglass", "Hourglass", Hourglass, ["time", "timer", "waiting"]),
  icon("house", "House", House, ["home", "property", "dwelling"]),
  icon("image", "Image", Image, ["photo", "picture", "media"]),
  icon("inbox", "Inbox", Inbox, ["mail", "messages", "inbox"]),
  icon("key", "Key", Key, ["lock", "security", "access"]),
  icon("keyboard", "Keyboard", Keyboard, ["type", "input", "keys"]),
  icon("lamp", "Lamp", Lamp, ["light", "lamp", "bright"]),
  icon("landmark", "Landmark", Landmark, ["building", "monument", "place"]),
  icon("languages", "Languages", Languages, ["translate", "multi", "speech"]),
  icon("laptop", "Laptop", Laptop, ["computer", "repair"]),
  icon("laptop", "Laptop", Laptop, ["computer", "desktop", "tech"]),
  icon("leaf", "Leaf", Leaf, ["garden", "eco"]),
  icon("library", "Library", Library, ["books", "collection", "media"]),
  icon("lightbulb", "Lightbulb", Lightbulb, ["electrician", "lighting"]),
  icon("link", "Link", Link, ["url", "connection", "share"]),
  icon("list", "List", List, ["items", "tasks", "collection"]),
  icon("loader", "Loader", Loader, ["loading", "spinner", "progress"]),
  icon("lock", "Lock", Lock, ["secure", "protected", "private"]),
  icon("luggage", "Luggage", Luggage, ["travel", "bag", "suitcase"]),
  icon("magnet", "Magnet", Magnet, ["attract", "metal", "force"]),
  icon("mail", "Mail", Mail, ["email", "contact"]),
  icon("mail", "Mail", Mail, ["email", "message", "inbox"]),
  icon("mailbox", "Mailbox", Mailbox, ["mail", "post", "box"]),
  icon("map", "Map", Map, ["location", "navigate", "guide"]),
  icon("maximize", "Maximize", Maximize, ["enlarge", "bigger", "expand"]),
  icon("medal", "Medal", Medal, ["award", "prize", "winner"]),
  icon("megaphone", "Megaphone", Megaphone, ["announce", "broadcast", "speak"]),
  icon("menu", "Menu", Menu, ["hamburger", "navigation", "list"]),
  icon("mic", "Mic", Mic, ["microphone", "audio", "voice"]),
  icon("microwave", "Microwave", Microwave, ["kitchen", "appliance"]),
  icon("microwave", "Microwave", Microwave, ["kitchen", "appliance"]),
  icon("milestone", "Milestone", Milestone, ["goal", "marker", "progress"]),
  icon("minimize", "Minimize", Minimize, ["shrink", "smaller", "collapse"]),
  icon("minus", "Minus", Minus, ["reduce", "remove", "less"]),
  icon("monitor", "Monitor", Monitor, ["screen", "display", "desktop"]),
  icon("moon", "Moon", Moon, ["night", "dark", "sleep"]),
  icon("move", "Move", Move, ["drag", "rearrange", "shift"]),
  icon("music", "Music", Music, ["audio", "song", "sound"]),
  icon("navigation", "Navigation", Navigation, ["nav", "directions", "map"]),
  icon("newspaper", "Newspaper", Newspaper, ["news", "paper", "print"]),
  icon("notebook", "Notebook", Notebook, ["notes", "journal", "write"]),
  icon("nut", "Nut", Nut, ["food", "health", "nutrition"]),
  icon("octagon", "Octagon", Octagon, ["shape", "stop", "badge"]),
  icon("option", "Option", Option, ["settings", "choice", "select"]),
  icon("orbit", "Orbit", Orbit, ["circle", "rotate", "space"]),
  icon("package", "Package", Package, ["delivery", "parcel"]),
  icon("package", "Package", Package, ["box", "delivery", "parcel"]),
  icon("paintbrush", "Paintbrush", Paintbrush, ["paint", "decorator"]),
  icon("palette", "Palette", Palette, ["colors", "art", "design"]),
  icon("pause", "Pause", Pause, ["stop", "hold", "media"]),
  icon("pencil", "Pencil", Pencil, ["write", "edit", "draw"]),
  icon("pentagon", "Pentagon", Pentagon, ["shape", "five", "star"]),
  icon("percent", "Percent", Percent, ["percentage", "ratio", "share"]),
  icon("phone", "Phone", Phone, ["call", "contact"]),
  icon("phone", "Phone", Phone, ["call", "contact", "mobile"]),
  icon("pi", "Pi", Pi, ["math", "ratio", "number"]),
  icon("piano", "Piano", Piano, ["music", "instrument", "sound"]),
  icon("pickaxe", "Pickaxe", Pickaxe, ["mining", "tool", "digg"]),
  icon("pill", "Pill", Pill, ["medicine", "drug", "health"]),
  icon("pin", "Pin", Pin, ["location", "marker", "sticky"]),
  icon("pizza", "Pizza", Pizza, ["food", "italian", "meal"]),
  icon("plane", "Plane", Plane, ["air", "travel", "flight"]),
  icon("play", "Play", Play, ["start", "media", "go"]),
  icon("plug", "Plug", Plug, ["electrician", "power"]),
  icon("plug", "Plug", Plug, ["power", "socket", "connect"]),
  icon("plus", "Plus", Plus, ["add", "new", "more"]),
  icon("pocket", "Pocket", Pocket, ["bag", "carry", "small"]),
  icon("pointer", "Pointer", Pointer, ["cursor", "click", "point"]),
  icon("popcorn", "Popcorn", Popcorn, ["snack", "movie", "food"]),
  icon("power", "Power", Power, ["on", "off", "energy"]),
  icon("presentation", "Presentation", Presentation, ["slides", "meet", "show"]),
  icon("printer", "Printer", Printer, ["print", "paper", "copy"]),
  icon("projector", "Projector", Projector, ["display", "screen", "present"]),
  icon("proportions", "Proportions", Proportions, ["size", "ratio", "measure"]),
  icon("puzzle", "Puzzle", Puzzle, ["game", "problem", "solve"]),
  icon("pyramid", "Pyramid", Pyramid, ["shape", "ancient", "geometry"]),
  icon("quote", "Quote", Quote, ["text", "citation", "dialog"]),
  icon("radio", "Radio", Radio, ["signal", "broadcast", "wave"]),
  icon("receipt", "Receipt", Receipt, ["payment", "bill", "invoice"]),
  icon("receipt", "Receipt", Receipt, ["invoice", "finance"]),
  icon("recycle", "Recycle", Recycle, ["reuse", "green", "eco"]),
  icon("redo", "Redo", Redo, ["repeat", "undo", "back"]),
  icon("refrigerator", "Refrigerator", Refrigerator, ["fridge", "appliance"]),
  icon("regex", "Regex", Regex, ["pattern", "search", "code"]),
  icon("registry", "Registry", ClipboardList, ["list", "register", "records"]),
  icon("repeat", "Repeat", Repeat, ["loop", "replay", "cycle"]),
  icon("reply", "Reply", Reply, ["respond", "answer", "back"]),
  icon("rewind", "Rewind", Rewind, ["back", "reverse", "media"]),
  icon("ribbon", "Ribbon", Ribbon, ["award", "decoration", "badge"]),
  icon("rocket", "Rocket", Rocket, ["launch", "growth"]),
  icon("rocket", "Rocket", Rocket, ["launch", "fast", "space"]),
  icon("route", "Route", Route, ["path", "directions", "navigate"]),
  icon("rows", "Rows", Rows2, ["grid", "table", "list"]),
  icon("rss", "RSS", Rss, ["feed", "news", "update"]),
  icon("ruler", "Ruler", Ruler, ["measure", "length", "size"]),
  icon("sailboat", "Sailboat", Sailboat, ["sea", "boat", "sail"]),
  icon("save", "Save", Save, ["keep", "store", "write"]),
  icon("scale", "Scale", Scale, ["balance", "weight", "measure"]),
  icon("scan", "Scan", Scan, ["read", "barcode", "camera"]),
  icon("school", "School", School, ["education", "learn", "university"]),
  icon("scissors", "Scissors", Scissors, ["salon", "tailor"]),
  icon("scissors", "Scissors", Scissors, ["cut", "trim", "edit"]),
  icon("search", "Search", Search, ["find", "look", "query"]),
  icon("section", "Section", Section, ["part", "divide", "area"]),
  icon("send", "Send", Send, ["send", "submit", "deliver"]),
  icon("server", "Server", Server, ["computer", "host", "cloud"]),
  icon("settings", "Settings", Settings, ["config", "options", "gear"]),
  icon("settings", "Settings", Settings2, ["configuration", "service"]),
  icon("share", "Share", Share, ["send", "give", "distribute"]),
  icon("shield", "Shield", Shield, ["protect", "safe", "security"]),
  icon("ship", "Ship", Ship, ["sea", "boat", "cargo"]),
  icon("shirt", "Clothing", Shirt, ["laundry", "tailor"]),
  icon("shovel", "Shovel", Shovel, ["dig", "garden", "tool"]),
  icon("shrink", "Shrink", Shrink, ["reduce", "smaller", "minimize"]),
  icon("shuffle", "Shuffle", Shuffle, ["random", "mix", "rearrange"]),
  icon("sigma", "Sigma", Sigma, ["math", "sum", "total"]),
  icon("signpost", "Signpost", Signpost, ["direction", "navigate", "map"]),
  icon("slash", "Slash", Slash, ["no", "not", "divide"]),
  icon("slice", "Slice", Slice, ["cut", "divide", "split"]),
  icon("sliders", "Sliders", SlidersHorizontal, ["settings", "filter", "adjust"]),
  icon("smartphone", "Smartphone", Smartphone, ["phone", "mobile", "cell"]),
  icon("smile", "Smile", Smile, ["happy", "happy", "face"]),
  icon("snail", "Snail", Snail, ["slow", "turtle", "animal"]),
  icon("snowflake", "Snowflake", Snowflake, ["cold", "winter", "ice"]),
  icon("snowflake", "Snowflake", Snowflake, ["ac", "cooling"]),
  icon("sofa", "Sofa", Sofa, ["furniture", "home"]),
  icon("sofa", "Sofa", Sofa, ["furniture", "home", "sit"]),
  icon("space", "Space", Space, ["blank", "gap", "distance"]),
  icon("sparkle", "Sparkle", Sparkle, ["shine", "magic", "star"]),
  icon("sparkles", "Sparkles", Sparkles, ["clean", "premium"]),
  icon("sparkles", "Sparkles", Sparkles, ["shine", "magic", "stars"]),
  icon("speaker", "Speaker", Speaker, ["sound", "audio", "music"]),
  icon("speech", "Speech", Speech, ["voice", "talk", "audio"]),
  icon("square", "Square", Square, ["shape", "block", "box"]),
  icon("star", "Star", Star, ["rating", "featured"]),
  icon("star", "Star", Star, ["favorite", "rate", "best"]),
  icon("stethoscope", "Stethoscope", Stethoscope, ["doctor", "health"]),
  icon("sticker", "Sticker", Sticker, ["label", "decoration", "note"]),
  icon("store", "Store", Store, ["shop", "retail"]),
  icon("store", "Store", Store, ["shop", "retail", "buy"]),
  icon("strikethrough", "Strikethrough", Strikethrough, ["cross", "cancel", "text"]),
  icon("subscript", "Subscript", Subscript, ["text", "small", "down"]),
  icon("sun", "Sun", Sun, ["day", "light", "bright"]),
  icon("sun", "Sun", Sun, ["day", "weather"]),
  icon("superscript", "Superscript", Superscript, ["text", "large", "up"]),
  icon("sword", "Sword", Sword, ["weapon", "fighter", "combat"]),
  icon("syringe", "Syringe", Syringe, ["medicine", "health", "needle"]),
  icon("table", "Table", Table, ["grid", "rows", "data"]),
  icon("tag", "Tag", Tag, ["offer", "price"]),
  icon("tag", "Tag", Tag, ["label", "category", "marker"]),
  icon("tags", "Tags", Tags, ["labels", "categories", "markers"]),
  icon("target", "Target", Target, ["goal", "aim", "objective"]),
  icon("tent", "Tent", Tent, ["camp", "outdoor", "sleep"]),
  icon("terminal", "Terminal", Terminal, ["code", "command", "console"]),
  icon("thermometer", "Thermometer", Thermometer, ["temperature", "health", "weather"]),
  icon("thermometer", "Thermometer", Thermometer, ["temperature", "ac"]),
  icon("ticket", "Ticket", Ticket, ["pass", "entry", "event"]),
  icon("timer", "Timer", Timer, ["time", "count", "limit"]),
  icon("toilet", "Toilet", Toilet, ["bathroom", "plumber"]),
  icon("toilet", "Toilet", Toilet, ["bathroom", "restroom"]),
  icon("tornado", "Tornado", Tornado, ["storm", "wind", "weather"]),
  icon("touchpad", "Touchpad", Touchpad, ["pad", "mouse", "track"]),
  icon("tractor", "Tractor", Tractor, ["agriculture", "farm"]),
  icon("tractor", "Tractor", Tractor, ["farm", "agriculture", "vehicle"]),
  icon("trash", "Trash", Trash, ["delete", "remove", "garbage"]),
  icon("trash", "Waste", Trash2, ["garbage", "cleaning"]),
  icon("trees", "Trees", Trees, ["forest", "nature", "wood"]),
  icon("trophy", "Trophy", Trophy, ["win", "prize", "award"]),
  icon("truck", "Truck", Truck, ["moving", "delivery"]),
  icon("truck", "Truck", Truck, ["delivery", "transport", "vehicle"]),
  icon("turtle", "Turtle", Turtle, ["slow", "animal", "shell"]),
  icon("tv", "Television", Tv, ["electronics", "repair"]),
  icon("tv", "TV", Tv, ["screen", "media", "television"]),
  icon("type", "Type", Type, ["text", "font", "write"]),
  icon("umbrella", "Umbrella", Umbrella, ["weather", "protection"]),
  icon("umbrella", "Umbrella", Umbrella, ["rain", "weather", "cover"]),
  icon("university", "Institution", University, ["education", "bank"]),
  icon("unlink", "Unlink", Unlink, ["disconnect", "detach", "remove"]),
  icon("unplug", "Unplug", Unplug, ["disconnect", "remove", "off"]),
  icon("upload", "Upload", Upload, ["send", "load", "import"]),
  icon("user", "User", User, ["person", "account", "profile"]),
  icon("users", "Users", Users, ["team", "community"]),
  icon("users", "Users", Users, ["people", "group", "team"]),
  icon("utensils", "Dining", Utensils, ["food", "restaurant"]),
  icon("utensils", "Utensils", Utensils, ["food", "eat", "dining"]),
  icon("variable", "Variable", Variable, ["math", "value", "code"]),
  icon("vault", "Vault", Vault, ["safe", "secure", "storage"]),
  icon("vibrate", "Vibrate", Vibrate, ["phone", "alert", "notification"]),
  icon("video", "Video", Video, ["media", "camera"]),
  icon("video", "Video", Video, ["movie", "camera", "media"]),
  icon("view", "View", View, ["see", "look", "watch"]),
  icon("voicemail", "Voicemail", Voicemail, ["voice", "message", "audio"]),
  icon("volume", "Volume", Volume, ["sound", "audio", "speaker"]),
  icon("vote", "Vote", Vote, ["election", "poll", "choice"]),
  icon("wallet", "Wallet", Wallet, ["money", "cards", "finance"]),
  icon("wallet", "Wallet", Wallet, ["payment", "finance"]),
  icon("wand", "Wand", Wand, ["magic", "spell", "star"]),
  icon("warehouse", "Warehouse", Warehouse, ["storage", "business"]),
  icon("warehouse", "Warehouse", Warehouse, ["storage", "inventory", "goods"]),
  icon("watch", "Watch", Watch, ["time", "clock", "wear"]),
  icon("waves", "Waves", Waves, ["water", "pool"]),
  icon("waves", "Waves", Waves, ["water", "sea", "ocean"]),
  icon("webcam", "Webcam", Webcam, ["camera", "video", "call"]),
  icon("webhook", "Webhook", Webhook, ["api", "connect", "hook"]),
  icon("weight", "Weight", Weight, ["heavy", "scale", "mass"]),
  icon("wheat", "Wheat", Wheat, ["food", "farm", "grain"]),
  icon("wifi", "Wi-Fi", Wifi, ["internet", "network"]),
  icon("wifi", "Wifi", Wifi, ["internet", "network", "wireless"]),
  icon("wind", "Wind", Wind, ["air", "ventilation"]),
  icon("wind", "Wind", Wind, ["air", "breeze", "weather"]),
  icon("wine", "Wine", Wine, ["drink", "alcohol", "grape"]),
  icon("wrench", "Wrench", Wrench, ["repair", "mechanic", "tool"]),
  icon("x", "X", X, ["close", "cancel", "remove"]),
  icon("youtube", "YouTube", Youtube, ["video", "media", "watch"]),
  icon("zap", "Zap", Zap, ["lightning", "fast", "electric"]),
  icon("zap", "Electric", Zap, ["electrician", "power"]),
];

export function resolveAdminIcon(name: string | null | undefined): LucideIcon {
  const normalized = String(name || "").trim().toLowerCase();
  return ADMIN_ICON_OPTIONS.find((option) => option.name === normalized)?.icon ?? Settings;
}

export function IconPicker({ value, onChange, disabled = false }: { value: string; onChange: (value: string) => void; disabled?: boolean }) {
  const [search, setSearch] = useState("");
  const filtered = useMemo(() => {
    if (!search.trim()) return ADMIN_ICON_OPTIONS;
    const q = search.toLowerCase();
    return ADMIN_ICON_OPTIONS.filter(
      (opt) => opt.label.toLowerCase().includes(q) || opt.name.toLowerCase().includes(q) || opt.keywords.some((k) => k.includes(q))
    );
  }, [search]);
  if (!filtered.length) return null;
  return (
    <div className="relative z-50">
      <input
        autoFocus
        className="w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm text-slate-800 outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-500"
        placeholder="Search icon..."
        value={search}
        onChange={(e) => setSearch(e.target.value)}
      />
      <div className="grid max-h-72 grid-cols-3 gap-2 overflow-y-auto pr-1 sm:grid-cols-4 md:grid-cols-5">
        {filtered.map((option) => {
          const Icon = option.icon;
          const active = value === option.name;
          return (
            <button
              key={option.name}
              title={`${option.label} (${option.name})`}
              className={`flex min-h-16 flex-col items-center justify-center gap-1 rounded-lg border px-2 py-2 text-center text-xs transition-colors disabled:opacity-50 ${
                active ? "border-blue-600 bg-blue-100 text-blue-800" : "border-slate-200 bg-white text-slate-600 hover:border-blue-300 hover:text-blue-700"
              }`}
              onClick={() => {
                if (!disabled) onChange(option.name);
              }}
            >
              <Icon size={17} />
              <span className="line-clamp-1 text-[10px] leading-tight">{option.label}</span>
            </button>
          );
        })}
      </div>
      {!filtered.length ? <p className="py-3 text-center text-sm text-slate-500">No matching icon.</p> : null}
    </div>
  );
}

